nasa/earthdata-search

edsc/plugins/datasource/cwic/src/js/Granules.jsx
I used the UAT CWIC collection and noticed that the granule paging was broken.
It turns out that for this collection, CWIC responses ```startIndex``` instead of ```startPage```. Hence the ```hasNextPage``` is false.
=> Fix granule paging.

app/assets/javascripts/models/ui/feedback.coffee, app/assets/javascripts/models/ui/project_list.js.coffee, app/assets/stylesheets/modules/data_access.css.scss, app/controllers/data_access_controller.rb, app/models/retrieval.rb, app/views/data_access/_access_error.html.erb, app/views/data_access/retrieval.html.erb, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/timeline_requests.yml, fixtures/cassettes/timeline_responses.yml, spec/features/data_access/background_ordering_spec.rb, spec/features/data_access/data_download_spec.rb
Some notes:
The notification is presented on the page, rather than via email, since I'd expect it to appear within a few seconds of the page loading. It comes with an error code that gets printed out for ops to reference in the logs.
All errors from submission get logged with patterns that make them easy to find via splunk. It could, in theory, be possible for an error to occur outside of the try/catch bounds we use to present error messages to the user, but it'd have to come from something obscure and global, like a coding error or database failure. Those would not be displayed to the user (because in that scope, there's no object to attach them to) but they'd still get logged.
=> EDSC-1068: Notify users when an order or service submission fails

app/views/layouts/application.html.erb
The existing FOIA link resolves to a [(presumably) old URL](http://www.hq.nasa.gov/office/pao/FOIA/agency/), one which does a meta redirect to [the new page](http://www.nasa.gov/FOIA/index.html).  Instead of routing FOIA request through the old URL, it is probably better to simply link to the new FOIA page.
This could be classified as a low-impact change, as it only affects one link on the main application layout.
=> Avoid FOIA Redirect Page by Direct Link

edsc/plugins/datasource/cwic/src/js/Granules.jsx
This is a quick add-on for EDSC-1235.  When a collection is being viewed and the granules are loading, the granules table would 'blink' (as in, appear, disappear, and then re-appear) very rapidly upon loading.  This is only with CWIC collections (so far as is known).
The 'callback' function that was removed from the AJAX success condition stored the function _load - which loads the data again.  Since it is a success callback, it only happens when the data is already successfully loaded!  It appears as if this call was actually causing granule data to load _twice_ within the table, and this was causing the 'blink'.
This particular blink bug is currently on production and so can be viewed by looking up 'USGS_EDC_EO1_ALI' (for convenience: …
=> EDSC-1235: Removed unnecessary call which was causing the granules table to blink

app/controllers/application_controller.rb, app/controllers/health_controller.rb, app/models/health.rb, lib/echo/urs_client.rb, spec/controllers/health_spec.rb, spec/helpers/mock_response.rb
A rescue method has been added to urs_client which will recover from a Faraday::Error::ConnectionFailed exception and will return the appropriate error.
To convenience testing, a parameter hook has been provided that can be used to trigger this error.  This technique uses the external site https://expired.badssl.com to throw the exception.  To trigger the error in the health check, try: http://edsc.dev/health?urs_test=true
=> EDSC-1200: Added Faraday rescue for connection failure

app/assets/javascripts/models/knockout_extensions.js.coffee
To address the default value being pruned (EDSC-1219):
- Removed skipValidation argument when constructing the form
- Removed ```projection param``` from the loaded model.
The ECHO-form PR can be found here:
https://github.com/nasa/edsc-echoforms/pull/21
=> EDSC-1130 EDSC-1219 Accept default projection param values.

app/assets/stylesheets/modules/data_access.css.scss
Go to /data/configure. The text color of access methods is #fff due to the recent facet list css changes.
=> EDSC-1313 Fix text color on data access configure page.

app/assets/javascripts/modules/nlp_parsing.js.coffee
When adding the splunk report I noticed that the "immediate_reentered" metric prematurally logged due to slow typing - the query is fired before user could finish typing the keyword: (edf_de -> edf_dev09 is one of the examples.)
This pull request addresses the issue.
=> EDSC-1296 Add variable to determine the end of typing.

config/portals.yml
change text in heading to ORNL DAAC/Search instead of ORNL DAAC/ORNL DAAC
Search is used on main EDSC
=> ORNL DAAC Portal: change text in heading

app/assets/javascripts/models/page/search_page.js.coffee
The issue is that the old scheme of /portals/[portal ID] became somewhat broken when we removed the landing page and set '/search' as our new forward page.  The portals functionality mirrors that of general functionality; it, too, must now end in '/search' to function properly.
This patch forwards portal calls without '/search' - as it used to be - to the new route.
=> EDSC-1504: Fixing Portal Access

app/presenters/collection_details_presenter_echo10.rb, app/presenters/collection_details_presenter_umm_json.rb, app/presenters/granule_details_presenter_echo10.rb, spec/features/collections/collection_metadata_spec.rb, spec/features/granules/granule_metadata_spec.rb
The solution of simply removing the tokens from the URLs had unintended side effects - this PR backs those changes out so that we can consider alternatives.
=> EDSC-1482: Backing out of initial solution for hiding user tokens

app/assets/javascripts/modules/help.js.coffee
There was an extra line in the 'Facets' popup that needed to be removed, and this PR also removes the term 'Client' from text as requested during demo.
=> EDSC-1500: Deleted copy/paste bug; nixed 'Client' from text

app/assets/javascripts/models/data/preferences.js.coffee, app/assets/javascripts/models/page/search_page.js.coffee
The site tour can potentially load despite being set to 'not show' due to a potential race condition involving a timer.  This new method of loading the site tour uses a 'deferred method' approach - this method adds precision to how the site tour must load after the user's preferences are fetched, and effectively removes the race condition.
=> EDSC-1531: Implemented deferred method to load site tour in order to remove potential race condition

app/assets/javascripts/models/data/collection.js.coffee, app/views/search/_collection_details.html.erb, spec/features/collections/collection_metadata_spec.rb
Find a collection that is visible after logging in. Open collection details page and the metadata dropdown. Mouseover or take a look at the html source, no token should appear.
=> EDSC-1482 Hide token from collection detail source code.

config/portals.yml
The ABoVE project would like a portal. ABoVE has data across DAACs.
I have omitted the ornl-daac-logo because it is not appropriate. If a logo is required, we should use the ABoVE logo. That will need to be added to repo.
=> adding ABoVE project portal

Gemfile.lock, app/assets/javascripts/models/page/search_page.js.coffee, app/assets/javascripts/modules/temporal/temporal_range_selection.js.coffee, app/views/search/index.html.erb, spec/features/temporal/temporal_selection_spec.rb
The issue is that the temporal dropdown is remaining open when the user selects the spatial dropdown or 'clear filters'; this is unexpected behavior for the user.
It's a tricky issue as the dropdown has to have special code to keep it open, as the datepicker within the temporal dropdown will close it unexpectedly when a date is choosen; this special code is what is erroneously keeping the dropdown open when the user clicks the spatial dropdown or 'clear filters'.
The fix was to modify how the dropdown stays open and coordinates with the datepicker, as well as new code triggered by the spatial dropdown and 'clear filters' that programmatically closes the temporal dropdown in the case it is still open.
=> EDSC-1448: Updated dropdown and datepicker behaviors

app/assets/javascripts/modules/temporal/temporal_range_selection.js.coffee, spec/features/temporal/temporal_selection_spec.rb
This fix moves the 'stopPropagation' routine out from the datepicker declarations in order to allow it to trigger in all applicable cases.  
This update was necessary as, within the previous PR, the stopPropagation routine was not firing in all cases - just  most of them.  This update should fix that issue.
=> EDSC-1488: Adjusted fix for updating datepicker and dropdown behavior

.travis.yml, Gemfile.lock, spec/features/data_access/opendap_retrieval_spec.rb, spec/features/granules/granule_filters_spec.rb, spec/spec_helper.rb
TravisCI is switching the default ubuntu to 14.04 'trusty'. We need to make changes accordingly.
However, due to the (very) old versions of test-related gems (capybara, rspec, capybara-webkit, etc.), the tests fails with broken pipe error.
Broken pipe error was fixed by making changes to ```.travis.yml``` to install gstreamer and related libs explicitly.
Then the build stalls due to possible capybara-webkit/qt issues. Travis seems to have some issues as well - they blogged a new option ```group: deprecated-2017Q3``` with sudo enabled. Also split the tests into more groups and increased the default wait time to 15 sec per suggestion by TravisCI.
Other approaches tried but didn't work out:
- use poltergeist driver
- use osx build platform (with qt@5.5)
- update test gems to higher/latest …
=> EDSC-1593 Make tests ready for 'trusty'

app/assets/javascripts/modules/map/geoutil.js.coffee
See the article for the detail of the algorithm. ~The polygon that the algorithm applied to in our code is not a closed polygon. So 180 degree is added when comparing to the ```delta```.~ In the algorithm, the second point in the array is used to calculate the last delta, heading, and sum. So ```latlngs[1]``` is ```push```ed to the array for calculation and then is ```pop```ed when ```delta``` is summed up.
In our tests, we only verify the existence of the path on the map. Therefore there is no test added.
~* A closed polygon has the same start and end point. For example: (1, 1), (3, 3), (4, 2), (1, 1).~
=> EDSC-1371 Fix polygon around pole issue.

app/controllers/users_controller.rb
The site tour is experiencing an issue wherein an **anonymous** user can select 'Do Not Show Again', close the page, and still see the splash screen when revisiting the site some time later.  This is due to the data being stored in the session object, which expires rather quickly.
This fix updates the anonymous user so that the preferences are stored in a cookie with a ten year expiration date.
=> EDSC-1531: Updated preferences to use cookie instead of session object in case of anonymous user

app/presenters/collection_details_presenter_umm_json.rb
The regex based conditionals that originally controlled this string cleansing became unwieldy, and so this patch provides a more direct and simpler solution.  Based upon these values (provided on the ticket):
blank 1 record
doi: 645 records
http://dx.doi.org 122 records
https://doi.org 1 record
10. 2368 records ('10.' is part of the URL and so is 'okay')
The code has been updated to 'clean' the string of these substrings (i.e., 'doi:', 'http://dx.doi.org', 'https://doi.org', ~~and '10.'~~), and then concatenate the remainder with a consistent 'https://dx.doi.org'. 
This has been tested with  'C1200237617-MMT_1' as well as 'C1200230663-MMT_1' (both on SIT).
=> EDSC-1645: Stripped out occurrences of dx.doi.org stuff in order to make string consistent

app/assets/javascripts/models/ui/granules_list.js.coffee, app/views/search/_granule_list.html.erb
I'd like someone to review this to see if I'm on the right track. I added a click event to the download button and had that trigger a `dataaccessevent` with a new Download method type called "direct_download." This should still populate the data access metric, but now we'll have a breakdown under download for this type.
I'm about 90% sure I've used the right methods from the other metrics calls, but I'd like someone with more experience on the GA side to take a look.
=> EDSC-1652: Direct Download GA Event

app/views/granules/prepare_script.html.erb
If the user attempts to execute a download script using 'bash', then the login was previously failing due to how bash interprets escape characters. Removing them from the script fixed the issue; further, using the other method of 'chmod 777' and then ./download.sh seems unaffected (meaning, works fine either way).
With this patch a user will be able to execute the download script with a simple 'bash download.sh' without setting the chmod first.
=> EDSC-1648: Fixed bug with using 'bash'

config/application.rb
This PR sets the x-frame-options to 'DENY' in an effort to pass certain security script checks.
=> EDSC-1683: Setting X-Frame-Options to 'Deny'

app/assets/javascripts/models/data/granule.coffee, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/granules_requests.yml, fixtures/cassettes/services_requests.yml, fixtures/cassettes/services_responses.yml, fixtures/cassettes/timeline_requests.yml, fixtures/cassettes/timeline_responses.yml, spec/features/granules/granule_list_spec.rb
The issue is that inappropriate links were being included into the 'Download' button of granules with multiple downloads. The links are provided as a bundled array which contains both the links to the data (which we want) as well as links to collection related data (which we do not want).
This array does not differentiate between the two except that the collection related data is all set to "inherited=true". Therefore, we can leverage this in order to filter them out, and only show the links to the granule specific data.
=> EDSC-1641: Bug fix, update to test and fixtures

app/assets/javascripts/models/data/granule.coffee, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/granules_requests.yml, fixtures/cassettes/services_requests.yml, fixtures/cassettes/services_responses.yml, fixtures/cassettes/timeline_requests.yml, fixtures/cassettes/timeline_responses.yml, spec/features/granules/granule_list_spec.rb, spec/helpers/page_helpers.rb
The issue is that a granule may have duplicate links towards the same file, with one using FTP and the other HTML.  This PR adds a filter mechanism to check and will suppress any FTP file links that already have HTML links present.
Collection 'C1444742099-PODAAC' was the one flagged in the ticket and is suitable for testing - check out the single granule 'dropdown' on production and see that there are two links - one to FTP and the other to HTML, which reference the same file name.  Contrast with this PR and see that it sends the user only to the HTML link and suppresses the FTP reference.
=> EDSC 1725: Created filter to remove 'FTP' duplicate links in granule downloads

app/assets/javascripts/models/data/granule.coffee, app/views/search/_granule_list.html.erb, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/granules_requests.yml, fixtures/cassettes/timeline_requests.yml, fixtures/cassettes/timeline_responses.yml, spec/features/granules/granule_list_spec.rb
https://bugs.earthdata.nasa.gov/browse/EDSC-1689
The collection I used to test is NSIDC-0481. The dropdown that appears when you click the Single Granule Download button on a granule in this collection should contain a list of filenames instead of "Download Link 1" "Download Link 2" etc., as was previously the case.
=> EDSC-1689: Improve link naming for multi-file granules

app/assets/javascripts/models/ui/project_list.js.coffee, app/assets/javascripts/models/ui/service_options_list.js.coffee, app/views/data_access/configure.html.erb, app/views/search/_delay_modal.html.erb, app/views/search/index.html.erb, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/granules_requests.yml, fixtures/cassettes/timeline_requests.yml, fixtures/cassettes/timeline_responses.yml, spec/features/granules/granule_list_spec.rb
This new modal will appear based upon the following tagging system:
```
"edsc.collection_alerts": {
"data": {
"limit": 10,
"message": "Optional message to be displayed in the modal"
}
}
```
When the 'Download Data' button is clicked from the granules page of a collection, a check is made to see if this tag is set for the targeted collection, and if so it checks whether the number of granules is greater than the 'limit'.  If it is - it shows the modal warning the user of the possible delay as well as shows the optional message, if present.
Collection 'C24931-LAADS' on SIT has this flag set and is suitable for testing.
=> EDSC 1733: Created New Modal for Collections that Might Cause Delays

app/assets/javascripts/models/data/service_options.js.coffee
This PR is an add-on for EDSC-1722: the purpose is to simply clear the 'title' hovertip once a method has been selected.
=> EDSC-1722: Updated title hovertip so that it is cleared after method selection

app/controllers/data_access_controller.rb
This additional logging will output the data request object when the 'Submit' button is clicked as per the following:
The following task is being submitted to delayed_job: {"query":"p=C179003620-ORNL_DAAC","collections":[{"id":"C179003620-ORNL_DAAC","params":"echo_collection_id=C179003620-ORNL_DAAC&sort_key%5B%5D=-start_date&page_size=20","serviceOptions":{"accessMethod":[{"method":"Order","type":"order","id":null}]},"form_hashes":[{"id":"order","form_hash":null}]}],"source":"p=C179003620-ORNL_DAAC&tl=1503944607!4!!&back=%2Fsearch%2Fgranules"}
It's worth noting that a test to check for this logging isn't available - I do not believe our test suites check logging (or are even able to).
=> EDSC-1599: Added additional logging during data retrieval

app/models/collection_extra.rb
EDSC had some code that was adding a Map Imagery badge on display, not by reading the collection's tag, to serve as an example. This isn't necessary anymore. Now, when searching for AST_L1T, you shouldn't see any Map Imagery badges. At some point those collections will have map imagery, just not yet.
=> EDSC-1771: Remove hardcoded GIBS tagging example.

app/presenters/collection_details_presenter_umm_json.rb, fixtures/cassettes/collections_requests.yml, fixtures/cassettes/concepts_requests.yml, fixtures/cassettes/concepts_responses.yml, fixtures/cassettes/services_requests.yml, fixtures/cassettes/services_responses.yml, spec/features/collections/collection_details_spec.rb
https://bugs.earthdata.nasa.gov/browse/EDSC-1717
There already existed a check (in _collection_details.html.erb) intended to make sure `related_urls` was not empty before displaying "Related URLs: View All Related URLs" on the collection details page. However, even if there were no Related URLs present in a collection, `related_urls` would never itself be an empty array - it was made up of objects to represent Collection URLs, Distribution URLs, Publication URLs, etc...  
The solution in this PR is to leave the check for an empty `related_urls` the same, and to set `related_urls` to actually be empty in the case where there are no Related URLs.
=> EDSC-1717: Sets related_urls to empty if there are no Related URLs

Procfile, app/controllers/data_access_controller.rb, app/models/retrieval.rb
The issue this ticket addresses is that job retrieval can become hung up if the single delayed_job worker becomes 'enthralled' with a long standing task, such as those coming from NSIDC.  The current implementation of data retrieval uses only a single lowly worker and one queue.
Edit: An earlier version of this PR required a modification to config/application.yml - this is no longer necessary.
My largest concern is with the instruction:
jobs: bundle exec bin/delayed_job --pool=Default:2 --pool=NSIDC,LPDAAC:2 --pool=*:2 run
I *believe* this will work, however my ability to test this line locally is limited.  It works well enough using 'start' instead of 'run' - when I use 'run', it keeps the process in the foreground (which it is supposed to do) however doesn't seem to start all the …
=> EDSC-1534: Implemented delayed_job queues and added additional workers

app/models/retrieval.rb
This PR adds the queue name to the logging message in the enqueue hook, and also clarifies the total jobs waiting log message
=> EDSC-1534: Added queue name to enqueue hook logging message

Procfile
This PR updates the Procfile to use the following delayed jobs configuration:
normal_jobs: bundle exec bin/delayed_job --pool=Default run
nsidc_jobs: bundle exec bin/delayed_job --pool=NSIDC run
lpdaac_jobs: bundle exec bin/delayed_job --pool=LPDAAC run
worker: bundle exec rake jobs:work
=> EDSC-1826: Updates Procfile configuration for Delayed Jobs

app/assets/stylesheets/modules/projects.css.scss, app/assets/stylesheets/modules/typography.css.scss, app/views/projects/show.html.erb, spec/features/projects/viewing_project_spec.rb
This one moves the replaces the Details button on the collection card in the project view. The collection details modal is now triggered by a View Granules link in the card.
=> EDSC-1898: Moving granules link to a new location on projects page

app/jobs/process_retrieval_job.rb, app/jobs/submit_catalog_rest_job.rb, app/services/esi_client.rb, spec/features/data_access/esi_order_spec.rb
Caveats:
* A polygon with many points ( like state/country boundaries found on the Internet ) will cause errors in the icesat2 subsetter
* Some KML/Shapefiles when converted to geojson have some characters that ESI complains about.
Will have to work with SDPS team to add more stability to these cases.
=> EDSC-2084: Added capability to use shapefile from search in esi order

static/src/js/components/OrderStatus/OrderStatusItemBody.js, static/src/js/components/ShapefileUploadModal/ShapefileUploadModal.js, static/src/js/components/ShapefileUploadModal/tests__/ShapefileUploadModal.test.js, static/src/js/components/SpatialDisplay/SpatialDisplay.js, static/src/js/containers/ShapefileDropzoneContainer/ShapefileDropzoneContainer.js, static/src/js/containers/ShapefileDropzoneContainer/__tests__/ShapefileDropzoneContainer.test.js
Updates the following:
* Tooltip for download script
* Shapefile labels have dropped the "ESRI" corporate branding.
* Upload method changed to `upload_shape` instead of `upload_esri`
=> EDSC-2479: Update tooltips and labels.

portals/podaac/config.json
The current PO.DAAC portal configuration has the wrong value for the dataCenter, with the result that no results are returned :-(. The correct name of the dataCenter in the collections query is "NASA/JPL/PODAAC", now replaced in the config.json, and returning 543 collections.
=> Fix podaac portal

portals/idn/config.json
Remove "Only include collections with granules" and "Include non-EOSDIS collections" filter check boxes (JIRA tickets: CMRSCI-3584 and EDSC-2485).
=> CMRSCI_3584: add line hideCollectionFilters to file

serverless/src/getAccessMethods/__tests__/handler.test.js, serverless/src/getAccessMethods/handler.js, static/src/js/actions/focusedCollection.js, static/src/js/actions/project.js, static/src/js/components/CollectionDetails/CollectionDetailsBody.js, static/src/js/components/CollectionDetails/__tests__/CollectionDetailsBody.test.js
`supportedOutputFormats` is being deprecated as of UMM-S 1.3.4 and is being moved within `supportedReformattings`. We already support `supportedReformattings` so this PR just removes/replaces references to `supportedOutputFormats` to prevent issues with the upcoming GraphQL update to UMM-S 1.3.4.
=> EDSC-2828: Prepare for deprecation of supported output formats (UMM-S 1.3.4)

static/src/js/components/SearchForm/SearchForm.js, static/src/js/components/SearchForm/__tests__/SearchForm.test.js
Implements #1223
I've followed the same pattern as for the panel open/close shortcut in [this PR](https://github.com/nasa/earthdata-search/commit/e58d0195f17441fca1e44ff9094368c3947464e3); I did wonder if it might be desirable to have shortcuts organised somewhere more centrally rather than scattered about between components, but I think that would be outside the scope of this issue.
Please let me know about any needed changes!
=> EDSC-2912: Adds keyboard shortcut to focus on search bar

static/src/js/components/GranuleResults/GranuleResultsHeader.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsHeader.test.js
Fixes: #1226 
In the collections.js file, in the updateFocusedCollectionGranuleFilters function, we only add a filter or overwrite an existing filter if at least one truthy value exists within the new filter. However if we clear the granule search bar it will pass a null value through to said function, which will never set due to the falsy nature of null. My fix passes an empty array for two reasons:
1) Normally the search input is converted into an array of values when not blank, so this keeps the datatype consistent regardless of content inside the search input.
2) An empty array is a truthy value, therefore it will successfully override the current filter inside the updateFocusedCollectionGranuleFilters function.
<details>
<summary><b>updateFocusedCollectionGranuleFilters</b> function …
=> EDSC-2898: Fix clearing existing granule filter in search bar

static/src/js/components/AdvancedSearchModal/AdvancedSearchModal.js, static/src/js/components/AdvancedSearchModal/__tests__/AdvancedSearchModal.test.js
Resolves: #1222 
Keyboard shortcut to toggle advanced search modal.
When the user presses 'a' key, it toggles advanced search modal.
AdvancedSearchModal.js and AdvancedSearchModal.test.js is changed.
Version 85.0.4183.121 (Official Build) (64-bit) (Ubuntu 18.04)
1. Press the 'a' on the homepage to toggle the advanced search modal.
=> EDSC-2911: Add keyboard shortcut to toggle advanced search modal

static/src/js/containers/TimelineContainer/TimelineContainer.js, static/src/js/containers/TimelineContainer/TimelineContainer.scss, static/src/js/containers/TimelineContainer/__tests__/TimelineContainer.test.js
This PR addresses this issue: https://github.com/nasa/earthdata-search/issues/1219
- Implements lazy loading Timeline Container component
- It uses React `lazy` and `Suspense` to handle lazy loading the timeline container component. 
- Adds the `Spinner` component as the fallback to display as the code for the timeline is being loaded.
- The search feature
This can be tested locally
1. Run the application
2. You can test this with the usage of the browser dev tools. 
- To test the fallback component: You can emulate a slow network in order to make it easier. This can be done on the network panel of your browser devtools. Then click one of the search results and validate that on the bottom of the page you see the Spinner. After …
=> EDSC-2672: Implement lazy loading on timeline container

package-lock.json, package.json, static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/EchoForm.js, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/AccessMethod/__tests__/EchoForm.test.js, static/src/js/components/ProjectPanels/ProjectPanels.js, static/src/js/components/ProjectPanels/__tests__/ProjectPanels.test.js, static/src/js/containers/ProjectPanelsContainer/ProjectPanelsContainer.js
Prepopulate temporal values in echoforms.
Send temporal values to the prepopulateValues prop for EDSCEchoForm component.
EchoForms.
http://localhost:8080/projects?p=C1705401930-NSIDC_ECS!C1705401930-NSIDC_ECS&pg[1][gsk]=-start_date&pg[1][m]=esi0&q=ICESat-2&qt=2020-03-08T18%3A57%3A13.890Z%2C2020-03-15T19%3A23%3A27.812Z&ff=Customizable&tl=1586120496!4!!
=> EDSC-2333: Prepopulate temporal values in echoforms

static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.js, static/src/js/components/GranuleResults/GranuleResultsTable.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsDataLinksButton.test.js
Fixes #1227 
~Not 100% sure of the possible cause but it was possibly because rowClick event of table triggering after the onClick of download button so it was immediately removing the dropdown menu.~
Edit: Changed implementation to use `e.stopPropogation()`
~It will impact the parts which has the same `onRowClick` function reference that I've made changes into. 
It checks if it has the `granule-results-data-links-button__button` class to check if it is the download button element.~
1. Search for a collection that has multi-file granules and click on it to load granules (NSIDC-0481 in 
2. Click on the download icon in the list view and observe that multiple files appear
3.  Confirm that clicking on those links downloads the …
=> EDSC-2895: Fix download granule dropdown in table view

cypress/integration/panels/behavior_spec.js, static/src/js/components/AdvancedSearchModal/AdvancedSearchModal.js, static/src/js/components/AdvancedSearchModal/__tests__/AdvancedSearchModal.test.js, static/src/js/components/GranuleResults/GranuleResultsHeader.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsHeader.test.js, static/src/js/components/KeyboardShortcutsModal/KeyboardShortcutsModal.js, static/src/js/components/KeyboardShortcutsModal/__tests__/KeyboardShortcutsModal.test.js, static/src/js/components/Panels/Panels.js, static/src/js/components/Panels/__tests__/Panels.test.js, static/src/js/components/SearchForm/SearchForm.js, static/src/js/components/SearchForm/__tests__/SearchForm.test.js, static/src/js/util/__tests__/triggerKeyboardShortcut.test.js, static/src/js/util/triggerKeyboardShortcut.js
Improves existing keyboard shortcuts.
- Fixes issue that caused accidental triggering of keyboard shortcuts when entering text in an input
- Swapping keydown to keyup, which prevents rapid triggering of the shortcut when a key is held
- Search input shortcut (/)
- Advanced search shortcut (a)
- Panel shortcut (])
- Shortcut shortcut (?)
- Existing text inputs (search, granule search, etc.)
- Can be tested in any environment
- Can be tested with any collection
1. Trigger any keyboard shortcut
2. Confirm the shortcut is triggered only when the shortcut is released
3. Focus in any text input
4. Try triggering a keyboard shortcut
5. Confirm the no shortcuts can be triggered
6. Unfocus from the input
7. Confirm the shortcuts work appropriately
=> EDSC-2911: Improving keyboard shortcuts

static/src/js/components/KeyboardShortcutsModal/KeyboardShortcutsModal.js
Removes unimplemented shortcut text
Remove text in `KeyboardShortcutsModal.js`
Keyboard shortcut modal
1. Load the application
2. Hit `?`
3. Note no reference to timeline toggle shortcut
=> EDSC-2911: Remove timeline shortcut text

serverless/src/generateGibsTags/__tests__/constructLayerTagData.test.js, serverless/src/generateGibsTags/__tests__/getSupportedGibsLayers.test.js, serverless/src/generateGibsTags/__tests__/handler.test.js, serverless/src/generateGibsTags/__tests__/mocks.js, serverless/src/generateGibsTags/constructLayerTagData.js, serverless/src/generateGibsTags/getSupportedGibsLayers.js, static/src/js/components/Map/GranuleGridLayer.js, static/src/js/util/map/__tests__/granules.test.js, static/src/js/util/map/granules.js
Limit the requests Leaflet makes for images to only those map tiles that exist in GIBS
Utilize the GIBS capabilities document to find the tile matrix height and width. Add that information into the GIBS tagging job and use that information to limit the requests Leaflet makes for granule imagery.
GIBS Tagging job
Leaflet
While viewing the dev tools network tab, view a collection with Map imagery and move the map to the edge of the map. Previously this would result in many image requests with a 400 error. Now you should not see any 400s for granule imagery. You may still see errors with Reference_Features or Reference_Labels in the URL
=> EDSC-2938: Prevent leaflet from requesting GIBS tiles that don't exist

static/src/js/components/CollectionResults/CollectionResultsListItem.js, static/src/js/components/CollectionResults/__tests__/CollectionResultsList.test.js, static/src/js/components/CollectionResults/skeleton.js
Resolves: #1229 
This PR adds a skeleton loading state for the collection results component that emulates the current skeleton design for granule items loading state.
I've created the new skeleton to replace the original loading state which was showing a "loading collections..." text in the collections panel while the collections loaded.
This only impacts the visual aspect of the application. Specifically, this only impacts the CollectionsResultsHeader component visually. 
- **DEV Environment:**
1. Navigate to the main search page (http://localhost:8080/search)
4. Observe that a skeleton of a collection result will appear in the CollectionResultsHeader component
5. Observe that the skeleton disappears after collections load.
6. Scroll down to the bottom of the collection results list.
7. …
=> EDSC-2515: Add collections loading state skeleton

static/src/js/util/url/__tests__/granuleFiltersEncoders.test.js, static/src/js/util/url/granuleFiltersEncoders.js
readableGranuleName wasn't being encoded before written to the URL, so if the field had a `#` in it, it would mess up the URL when navigating between pages
Use `encodeURIComponent` to encode the field, and `decodeURIComponent` to decode it.
- Search for C14758250-LPDAAC_ECS (prod collection)
- Click to load granules
- Use Granule Search to search for a single granule (AST_L1A#00310122020232154_10132020080234.hdf)
- Note that only 1 granule returns
- Click download
- Note that 1 collection and 1 granule are in the project
- Click download
- Note that only one granule is returned in the order
=> EDSC-2919: Encode readableGranuleName before writing to URL

serverless/src/util/__tests__/getEdlConfig.test.js, serverless/src/util/getEdlConfig.js, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.scss, static/src/js/containers/GranuleImageContainer/GranuleImageContainer.js, static/src/js/containers/GranuleImageContainer/__tests__/GranuleImageContainer.test.js
Fixes the granule download link list by adding a max height and making it scrollable.
This is a bug fix related multiple granule links when there are too many and the bottom of the list isn't visible.
Added a bit of CSS to utilize scrolling to ensure access to all the links available.
Granule card list and table.
=> EDSC-2882: Ensure all granule links are visible (via scrolling)

static/src/js/components/GranuleResults/GranuleDownloadButton.js, static/src/js/components/GranuleResults/__tests__/GranuleDownloadButton.test.js, static/src/js/reducers/__tests__/project.test.js, static/src/js/reducers/project.js
Selected granule outlines are not showing on the project page.
The granules weren't visible because the project collection was set to not visible by default. This PR changes that to be true by default. It sets the default in the reducer, and ensures the Download All button sets it to true
Replicate:
https://search.uat.earthdata.nasa.gov/search/granules?p=C55424-LPDAAC_TS2!C55424-LPDAAC_TS2&pg[1][a]=75578!LPDAAC_TS2&pg[1][gsk]=-start_date&pg[1][m]=echoOrder0&m=42.17535863612541!-94.11328125!5!1!0!0%2C2&ff=Map%20Imagery&tag_key=gov.nasa.eosdis&tl=1585085356!4!!
Open link and select 'Download 1 Granule'. Selected granule outline is not displayed on project page.
=> EDSC-2893: Default project collections visibility to true

static/src/js/util/__tests__/portals.test.js, static/src/js/util/portals.js
Portal configs were not properly being merged together with their parent configs. This resulted in some values (like `showOnlyGranulesCheckbox` and `showNonEosdisCheckbox`) not being disabled in EDSC when portals disabled them in their config (like `idn` portal).
Fixed the merge logic for portal configs.
Portals.
Load the IDN portal `/portals/idn`
See that the `Only include collections with granules` and `Include non-EOSDIS collections` checkboxes are hidden
=> EDSC-2951: Merge portal configs successfully

static/src/js/actions/__tests__/urlQuery.test.js, static/src/js/actions/urlQuery.js
Naming a project and then refreshing the page was causing nothing to load. This fixes that bug.
A return statement in the action that loads the named project's parameters from lambda was causing none of our 'get' actions to be called to load the data. I removed that return statement and updated the code that uses the decoded parameters.
Name a project, refresh the page
=> EDSC-2948: Continue loading page after named project params are loaded

serverless/src/getRetrieval/__tests__/handler.test.js, serverless/src/getRetrieval/__tests__/mocks.js, serverless/src/getRetrieval/handler.js, serverless/src/getRetrievalCollection/__tests__/handler.test.js, serverless/src/getRetrievals/__tests__/handler.test.js, serverless/src/getRetrievals/handler.js, serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitCatalogRestOrder/handler.js, static/src/js/actions/__tests__/retrieval.test.js, static/src/js/actions/__tests__/retrievalHistory.test.js, static/src/js/actions/retrieval.js, static/src/js/actions/retrievalHistory.js, static/src/js/components/DownloadHistory/DownloadHistory.js, static/src/js/components/DownloadHistory/__tests__/DownloadHistory.test.js, static/src/js/components/OrderStatus/OrderStatus.js, static/src/js/components/OrderStatus/__tests__/OrderStatus.test.js, static/src/js/components/SecondaryToolbar/SecondaryToolbar.js, static/src/js/components/SecondaryToolbar/__tests__/SecondaryToolbar.test.js, static/src/js/containers/DownloadHistoryContainer/DownloadHistoryContainer.js, static/src/js/containers/DownloadHistoryContainer/__tests__/DownloadHistoryContainer.test.js, static/src/js/selectors/__tests__/earthdataEnvironment.test.js, static/src/js/selectors/earthdataEnvironment.js, static/src/js/util/url/url.js
Adds support for earthdata environment on /downloads
Download status page, download history page
View the downloads page with the `ee` param
=> EDSC-2964: Adds support for earthdata environment on /downloads

serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/addTag.js
The addTag lambda was not reading the correct CMR response for collection searches.
Added the correct response (`body.feed.entry`)
Tagging
=> EDSC-2938: Fix addTag with correct CMR response

serverless/src/getAccessMethods/__tests__/handler.test.js, serverless/src/getAccessMethods/handler.js, static/src/js/components/AccessMethod/AccessMethod.js
Prevents calling `componentWillReceiveProps` for access methods because it isn't needed now that we offer a `None` option and we don't set a 'default'.
Removed the `componentWillReceiveProps` method.
Changing supported output format and supported output projection.
See EDSC-2970 comments.
=> EDSC-2970: Don't set default values for output format or projection

serverless/src/generateCollectionCapabilityTags/__tests__/getCollectionCapabilities.test.js, serverless/src/generateCollectionCapabilityTags/__tests__/handler.test.js, serverless/src/generateCollectionCapabilityTags/getCollectionCapabilities.js, serverless/src/generateGibsTags/__tests__/constructLayerTagData.test.js, serverless/src/generateGibsTags/__tests__/getSupportedGibsLayers.test.js, serverless/src/generateGibsTags/__tests__/handler.test.js, serverless/src/generateGibsTags/__tests__/mocks.js, serverless/src/generateGibsTags/constructLayerTagData.js, serverless/src/generateGibsTags/getSupportedGibsLayers.js, serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/addTag.js, static/src/js/components/Map/GranuleGridLayerExtended.js, static/src/js/components/Map/__tests__/GranuleGridLayerExtended.test.js
Matrix Tile Sets are too big for CMR tags, so we're removing it and adding new endpoints to the visualization app.
Removed the injection of matrix tile sets into the gibs tag.
GIBS Imagery.
=> EDSC-2938: Removes matrix tile sets from tags

serverless/src/edlLogin/__tests__/handler.test.js, serverless/src/edlLogin/handler.js
The edlLogin lambda was parsing arrays when examining the `state` parameter, causing the array indices to be lost
Added the `parseArrays: false` option to the `parse` command in edlLogin
Projects
While logged out, add a single granule to your project.
Click the Earthdata Login button, or Download button.
When redirected back to EDSC, you should only see the single granule in your project
=> EDSC-2978: Keeps project collection parameters through EDL login redirects

serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/addTag.js
The addTag job was throwing errors because it was trying to add tag associations when there were no collections matching the search criteria
Change ```if (!collections) return false``` to ```if (!collections.length) return false```
Tagging
=> EDSC-2977: Prevent tag associations when no collections results are returned

static/src/js/reducers/__tests__/facetsParams.test.js, static/src/js/reducers/facetsParams.js
Selecting an autocomplete suggestion was selecting the value as a facet or adding the selected facet below the search field
Fixed the reducer to handle spreading out the previous state when that state is undefined
Autocomplete, Facets
Type `MODI` into the search field
Select `Instrument: MODIS`
The autocomplete should be selected and the Instrument facet for MODIS should be applied
=> EDSC-2975: Fixes the autocomplete facet behavior

static/src/js/util/url/__tests__/facetEncoders.test.js, static/src/js/util/url/facetEncoders.js
Facets with `&` in the name were not being encoded before written to the URL. Refreshing the page (or sharing the URL) would result in incorrect results
Encode/decode facet names when writing/reading them from the URL
Facets
Select a facet with a `&` in the name. In prod the organization `Level-1 and Atmosphere Archive & Distribution System (LAADS)` works
Refresh the page and note the facet is still applied and results are returned correctly
=> EDSC-2867: Encodes facets before writing them to the URL

static/src/js/util/granules.js
Excluded granules are being included in projects, they should be excluded
Include the `excludedGranuleIds` when loading a project collection's granule params
Projects
Excluded a granule from search results
Add the entire collection to your project and navigate to the project page
The excluded granule should not be included in your project page granules
=> EDSC-2961: Include the excludedGranuleIds when loading a project collection's granule params

migrations/1605032948012_add-error-to-retrieval-orders.js, serverless/src/fetchCatalogRestOrder/__tests__/handler.test.js, serverless/src/fetchCatalogRestOrder/handler.js, serverless/src/getRetrievalCollection/handler.js, serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitCatalogRestOrder/handler.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/handler.js, serverless/src/submitLegacyServicesOrder/__tests__/handler.test.js, serverless/src/submitLegacyServicesOrder/handler.js, sharedUtils/__tests__/parseError.test.js, sharedUtils/parseError.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js
EDSC Order Status should reveal full error message
Save errors generated when an order is created, display that error on the order status page
Orders
=> EDSC-2261: Displays errors generated when creating new retrievals

static/src/js/actions/__tests__/viewAllFacets.test.js, static/src/js/actions/viewAllFacets.js, static/src/js/components/Facets/FacetsModal.js, static/src/js/util/facets.js
The `View All Facets` modal is not being populated with facets results
The View All request was not happening with the correct parameters because the request was using outdated redux state to build the parameters, and we were not populating the modal with the values return. Also some additional cleanup of the view all facets logic
View All Facets
Expand the `Platforms` facet group and click the `View All` link. You should see significantly more facets than the expanded group shows.
Additionally test selecting and deselecting the facets from the modal
=> EDSC-2987: Fixes view all facets

serverless/src/fetchOptionDefinitions/__tests__/handler.test.js, serverless/src/fetchOptionDefinitions/handler.js, serverless/src/generateCollectionCapabilityTags/__tests__/handler.test.js, serverless/src/generateCollectionCapabilityTags/handler.js, serverless/src/generateSubsettingTags/__tests__/handler.test.js, serverless/src/generateSubsettingTags/getServiceOptionDefinitionIdNamePairs.js, serverless/src/generateSubsettingTags/handler.js, serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/__tests__/removeTag.test.js, serverless/src/processTag/addTag.js, serverless/src/processTag/removeTag.js, serverless/src/util/cmr/__tests__/getSingleGranule.test.js, serverless/src/util/cmr/__tests__/pageAllCmrResults.test.js, serverless/src/util/cmr/getSingleGranule.js, serverless/src/util/cmr/pageAllCmrResults.js
Tagging calls use a system token, and need to use the 'Echo-Token' header instead of the 'Authorization' header
Tagging
=> EDSC-2977: Use 'Echo-Token' header for tagging calls

serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/__tests__/constructOrderPayload.test.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/constructOrderPayload.js, serverless/src/submitLegacyServicesOrder/__tests__/constructOrderPayload.test.js, serverless/src/submitLegacyServicesOrder/__tests__/handler.test.js
Fixes granule request that is made as part of the harmony order submission.
The Authorization header was missing the `Bearer ` prefix, I've added that.
Harmony order submissions.
Submitting harmony orders should now work.
=> EDSC-2864: Corrects bearer token usage when submitting harmony orders

static/src/js/components/SpatialSelection/SpatialSelection.js, static/src/js/components/SpatialSelection/__tests__/SpatialSelection.test.js
After downloading data when spatial drawn, if the `Back to Project` & `Back to Search` buttons are used, selecting a new drawing from the spatial selection dropdown under the search bar throws an error and doesn't allow drawing a new spatial selection.
The code that triggers the leaflet.draw toolbar should check that the right draw mode exists before trying to enable it
Map
Search for any dataset and load granules
Draw a rectangle over your study area. (Mine was between West Palm Beach and Fort Lauderdale Florida but I think any location should work)
Add a couple of granules
Click on Download X granules button
Click on green download the data button.
Click "Back to Project"
Click "Back to search"
Click on the same data originally selected
Move to another study area. This time I am looking …
=> EDSC-2966: Fixes bug in selecting a new spatial drawing after downloading project

static/src/js/components/CollectionResults/CollectionResultsItem.js, static/src/js/components/CollectionResults/CollectionResultsItem.scss, static/src/js/components/CollectionResults/__tests__/CollectionResultsItem.test.js
Fixes bug where customizable tooltips on collection search results were positioned incorrectly.
Removed css override in favor of using the popperConfig on the OverlayTrigger component to override default positioning.
- Collection results list items
- **Collection to test with:** Any that support customization
1. Load search results containing the "customizable" tag
2. Confirm tooltip is positioned correctly when the icon is hovered
=> EDSC-2990: Fixing customizable tooltip positioning

serverless/src/getAccessMethods/getServiceOptionDefinitions.js
Missed one of the param name changes from `qs` to `params` when switching from request-promise to axios
=> EDSC-2986: Fixes axios param name

sharedUtils/__tests__/orderStatus.test.js, sharedUtils/orderStatus.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/OrderStatusItem.scss, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js
Harmony jobs can come back with a status of `canceled`, which we account for `cancelled`. EDSC also didn't have a canceled state (previously was `failed`)
Adds a `canceled` order status and moves canceled status to it instead of `failed`
Harmony orders
Have a Harmony order canceled.
View order status page for that order
=> EDSC-2962: Adds 'canceled' to list of failed order statuses

package-lock.json, package.json
Moves the `aws-sdk` from `devDependencies` to `dependencies`
=> EDSC-3011: Fixes dependency

static/src/js/actions/__tests__/authToken.test.js, static/src/js/actions/__tests__/collections.test.js, static/src/js/actions/__tests__/focusedCollection.test.js, static/src/js/actions/__tests__/focusedGranule.test.js, static/src/js/actions/__tests__/granules.test.js, static/src/js/actions/__tests__/preferences.test.js, static/src/js/actions/__tests__/project.test.js, static/src/js/actions/__tests__/timeline.test.js, static/src/js/actions/__tests__/viewAllFacets.test.js, static/src/js/actions/authToken.js, static/src/js/actions/collections.js, static/src/js/actions/focusedCollection.js, static/src/js/actions/focusedGranule.js, static/src/js/actions/granules.js, static/src/js/actions/index.js, static/src/js/actions/preferences.js, static/src/js/actions/project.js, static/src/js/actions/timeline.js, static/src/js/actions/viewAllFacets.js
updateAuthTokenFromHeaders is unnecessary as the authToken does not change when the EDL token is refreshed
=> EDSC-3000: Removes updateAuthTokenFromHeaders

serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitLegacyServicesOrder/__tests__/constructOrderPayload.test.js, sharedUtils/__tests__/prepareGranuleAccessParams.test.js, sharedUtils/prepareGranuleAccessParams.js
When using additive granules for a retrieval, we only send the `concept_id` parameter to retrieval those granules. CMR has a default page size of 10, so only the first 10 granules are added to the request if the user added more than 10.
Include `page_size=2000` (the max page size for CMR) to granule requests when building a retrieval payload
Retrievals
Using the additive model, add more than 10 granules to a retrieval
Submit the retrieval and ensure all granules are processed
11 granules have been added here https://search.earthdata.nasa.gov/search/granules?p=C190733714-LPDAAC_ECS!C190733714-LPDAAC_ECS&pg[1][a]=1982455090!1982456259!1982455395!1982455802!1982456179!1982456277!1982456652!1982455235!1982455888!1982456347!1982455758!LPDAAC_ECS&pg[1][v]=t&pg[1][gsk]=-start_date&q=C190733714-LP …
=> EDSC-3009: Adds page_size parameter to additive retrieval requests

static/src/js/components/SpatialDisplay/SpatialDisplay.js, static/src/js/components/SpatialDisplay/__tests__/SpatialDisplay.test.js
Pasting spatial coordinates didn't work if the pasted value didn't follow the decimal limit
This change will trim the pasted value to fit the regex that enforces the decimal limit
Manual spatial entry
Copy a spatial value with more than 5 decimal places, like `45.859602, -94.286033`
Paste that value into the manual entry spatial field, value should be trimmed to `45.85960,-94.28603`
Repeat for point/rectangle/circle fields
=> EDSC-2859: Allow pasting spatial coordinates that exceed the decimal limit

serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/addTag.js
`request-promise` automatically added headers when `form` was used, we needed to add the header when we switched to Axios and missed this one.
Added the correct header to the CMR request.
Tagging background jobs.
=> EDSC-2986: Adds content type to CMR request

static.config.json, static/src/js/components/GranuleResults/GranuleResultsTable.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsTable.test.js, static/src/js/util/formatGranulesList.js
Remove "Orig. Format" from granule results table
Granule results table view
View granule results table view, `Orig. Format` column will be removed
=> EDSC-2939: Remove "Orig. Format" from granule results table

serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/__tests__/removeTag.test.js, serverless/src/processTag/addTag.js, serverless/src/processTag/handler.js, serverless/src/processTag/removeTag.js
Adds content type header for cmr calls.
=> EDSC-2986: Adds content type for remaining calls

static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/SearchPanels/SearchPanels.js
A couple of icons were missing, overlooked in the initial EDSC-2909 effort
Icons need to be passed as Icons from the `react-icons/fa` library, not as strings
Cwic granules page, download page
=> EDSC-2909: Fixes missing icons

serverless/src/generateGibsTags/__tests__/getSupportedGibsLayers.test.js, serverless/src/generateGibsTags/__tests__/handler.test.js, serverless/src/generateGibsTags/handler.js, serverless/src/processTag/__tests__/addTag.test.js, serverless/src/processTag/__tests__/removeTag.test.js, serverless/src/processTag/addTag.js, serverless/src/processTag/removeTag.js
Prevent errors in the processTag lambda by ensuring that we dont merge custom products into the Gibs job when not in production.
=> EDSC-2986: Ignore custom products when not in production

static/src/js/components/CollapsePanel/CollapsePanel.js, static/src/js/components/CollapsePanel/CollapsePanel.scss, static/src/js/components/CollapsePanel/__tests__/CollapsePanel.test.js, static/src/js/components/CollectionResults/CollectionResultsItem.scss, static/src/js/components/CustomToggle/MoreActionsToggle.scss, static/src/js/components/DataQualitySummary/DataQualitySummary.js, static/src/js/components/DataQualitySummary/DataQualitySummary.scss, static/src/js/components/FormFields/AccessMethodRadio/AccessMethodRadio.scss, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.js, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.scss, static/src/js/components/MoreActionsDropdown/MoreActionsDropdown.scss, static/src/js/components/ProjectCollections/ProjectCollectionItem.scss
This PR addresses an issue where lists of granule links on granule search results were overflowing their container. There are also a few small css tweaks improving the display of icons on the project page.
Tweak css to correctly override the default boostrap class causing the issue.
Granule search results and the project page
- **Environment for testing:** Prod
- **Collection to test with:** C1711924822-LPCLOUD
1. Visit /search/granules?p=C1711924822-LPCLOUD&pg[0][gsk]=-start_date&q=hls&m=-8.718732723754655!-159.374267578125!7!1!0!0%2C2&tl=1595431927!4!!
2. Open the links on any granule
3. Confirm the list scrolls when links exist outside of the dropdown
4. Confirm the icons on the project page display as intended
=> EDSC-3046: Granule link overflow fix

serverless/src/util/cmr/getSingleGranule.js
Collection capabilities tags were not being generated correctly
During the switch from request-promise to axios we missed one request changing the `form` parameter to `data`
Collection capabilities tagging
=> EDSC-3052: Fixes collection capabilities tagging

.github/workflows/ci.yml, package-lock.json, package.json, serverless.yml, static/src/js/components/AccessMethod/EchoForm.js, static/src/js/components/ProjectCollections/ProjectCollections.js, static/src/js/components/ProjectCollections/__tests__/ProjectCollections.test.js, static/src/js/containers/UrlQueryContainer/UrlQueryContainer.js, static/src/js/containers/UrlQueryContainer/__tests__/UrlQueryContainer.test.js, static/src/js/util/accessMethods.js
ESI (customize) orders need to be customized before submission to avoid unnecessary processing with providers. This code disables the download data button for ESI orders until a customization option has been selected
Customize orders
Load the project page with a customizable collection.
Select the Customize access method.
You will see the Download Data button disabled and a message you need to select a customization option or choose a different access method.
If you have previously download that collection, reset the form to see the message.
The Download Data button will be enabled after applying a customization.
=> EDSC-2055: Disable download button on projects with an esi order that hasn't been customized

static/src/js/util/__tests__/granules.test.js, static/src/js/util/granules.js
Projects with HUC spatial are unable to submit.
HUC spatial is saved in the store as a string, but we save regular spatial as an array of strings. When we prepare granule params we need to wrap HUC spatial in an array to match the regular spatial params
Projects with HUC spatial
Use advanced search to find a HUC polygon (HUC 020801 will work)
Find a collection that matches that spatial and try to submit a project with that collection.
The project should submit successfully
=> EDSC-3061: Fixes project submission with HUC s patial

static/src/js/util/files/generateDownloadScript.js
When I try running this download script under Ubuntu it doesn't run.  It is targeting sh and some of the commands used in the script are bash specific.  I retested the script under bash and it runs well.
=> Update generated download script to use bash instead of sh

package-lock.json, package.json, static/src/js/components/Map/GranuleGridLayer.js, static/src/js/components/Map/GranuleGridLayerExtended.js, static/src/js/containers/MapContainer/MapContainer.js
Cache GIBS imagery in browser memory
Map imagery
Load a collection with map imagery, open devtools and clear the network requests.
Moving the map will redraw the images, but you won't see any network requests coming from `GranuleGridLayerExtended.js`
Changing the map zoom you will see requests from `GranuleGridLayerExtended.js`, but when you return to the initial zoom you won't see any requests
=> EDSC-3077: Caches GIBS imagery in memory

schemas/sitePreferencesSchema.json
Fixes an incorrect default value for the projection field in map preferences
=> EDSC-3036: Fix projection preference default

serverless/src/util/database/getDbCredentials.js
The EDSC team logs into their local database without username/password. If a dev needs to use username/password they weren't able to read those values from their `secret.config.json`. This change fixes that issue
=> EDSC-3091: Fix getDbCredentials for dev environment

static/src/js/components/Map/GranuleGridLayerExtended.js
When our GIBS tag includes a match field that is missing in the granule metadata, we weren't handling that and an error page was being shown
Check for the existence of the metadata before continuing 
Granules drawn on the map
Load the granules results page for this collection (in prod) `C1931660485-NSIDC_ECS`
=> EDSC-3112: Fixes bug when drawing granules with missing metadata

static/src/js/reducers/__tests__/query.test.js, static/src/js/reducers/query.js
Changes the default collection sort to `usage`, or technically `-usage_score`
Collection results
Load EDSC, see the collection results are sorted by usage
=> EDSC-3096: Set the default collection search to 'usage'

static/src/js/components/Preferences/PreferencesNumberField.js, static/src/js/components/Preferences/__tests__/PreferencesNumberField.test.js
On the preferences form, `0` was not accepted as a valid number in number fields
`0` was being evaluated as falsey in the check for if the value was a number, I fixed that problem
Preferences form
Set the preferences form latitude or longitude to `0`, no error is shown and the value is able to be saved.
=> EDSC-3094: Allow 0 values in preferences form

static/src/js/components/CollectionDetails/CollectionDetailsBody.js, static/src/js/components/CollectionDetails/__tests__/CollectionDetailsBody.test.js
Only show reformatting options supported be EDSC, also don't show duplicates of reformatting options in the list
Collection details
Visit https://search.earthdata.nasa.gov/search/granules/collection-details?p=C1000001167-NSIDC_ECS&m=-0.140625!0.140625!2!1!0!0%2C2&ff=Customizable&tl=1598556866!4!!
Ensure no duplicates are present, and the correct options are there from the services EDSC supports (ESI, OPeNDAP, ECHO ORDERS, and Harmony)
=> EDSC-3092: Only show reformatting options supported be EDSC

bin/deploy-bamboo.sh
Deployment script is failing but nothing has changed, attempting to allow errors to be returned to see if it can get beyond this step that has always has the same output.
=> EDSC-2626: Allow errors, for now.

package-lock.json, package.json, static/src/js/actions/__tests__/granules.test.js, static/src/js/util/request/openSearchGranuleRequest.js
Deployment of opensearch granule retrieval is giving us trouble.
- Installs `ws` because someone can't figure out their dependencies.
- Downgrades the lockfile from 2, down to 1 allowing use of @macrouch fork of react-leaflet-draw
- Resets the API gateway path as the deployment.. seems to have figured itself out
OpenSearch granule retrieval.
=> EDSC-2626: Attempt to patch up deployment issues with AWS / Serverless

static/src/js/components/Map/LayerBuilder.js, static/src/js/components/Map/__tests__/LayerBuilder.test.js
The GIBS URL we are generating for our map tiles is using an older parameter. This PR updates that parameter to what it needs to be.
Map
Load EDSC, ensure map tiles (blue marble, placenames, etc.) are visible
=> EDSC-3160: Updates GIBS URL for map layers

static/src/js/actions/__tests__/subscriptions.test.js, static/src/js/containers/SubscriptionsBodyContainer/__tests__/SubscriptionsBodyContainer.test.js, static/src/js/selectors/__tests__/query.test.js, static/src/js/util/__tests__/subscriptions.test.js, static/src/js/util/subscriptions.js
CMR can't decode URL encoded subscription queries
Send subscription queries as URL parameters strings, but not encoded.
Subscriptions
Create a new subscription, ensure it is created successfully
Check the network tab for the request and ensure the `query` parameter is not encoded
=> EDSC-3081: Updates subscription queries to not be encoded strings

static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js
EGI order info has a message field that can provide the user with additional information about the order. This field is now displayed on the order status page
Order status
=> EDSC-2983: Display 'message' field from EGI on order status page

migrations/1619617419390_update-user-tokens-text.js
Our database needs to store larger tokens from EDL. This updates those fields to be `text` types
=> EDSC-3115: Update user_tokens table to accept longer EDL tokens

serverless-configs/aws-functions.yml
Adds the timeout configuration to the fetch* Lambdas to prevent timeouts when retrieving status payloads for orders.
=> EDSC-3164: Adds application wide value for Lambda Timeout

jest.config.js, static/src/css/vendor/bootstrap/overrides/_dropdown.scss, static/src/js/components/Button/Button.js, static/src/js/components/Button/Button.scss, static/src/js/components/Button/__tests__/Button.test.js, static/src/js/components/EDSCTabs/EDSCTabs.js, static/src/js/components/EDSCTabs/EDSCTabs.scss, static/src/js/components/EDSCTabs/__tests__/EDSCTabs.test.js, static/src/js/components/GranuleResults/GranuleResultsBody.js, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.js, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.scss, static/src/js/components/GranuleResults/GranuleResultsItem.js, static/src/js/components/GranuleResults/GranuleResultsList.js, static/src/js/components/GranuleResults/GranuleResultsListBody.js, static/src/js/components/GranuleResults/GranuleResultsListItem.js, static/src/js/components/GranuleResults/GranuleResultsTable.js, static/src/js/components/GranuleResults/GranuleResultsTableHeaderCell.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsBody.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsDataLinksButton.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsItem.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsList.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsTable.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsTableHeaderCell.test.js, static/src/js/components/SubscriptionsList/__tests__/SubscriptionsList.test.js, static/src/js/containers/GranuleResultsBodyContainer/GranuleResultsBodyContainer.js, static/src/js/util/__tests__/formatGranulesList.test.js, static/src/js/util/formatGranulesList.js, static/src/js/util/granules.js
Adds AWS S3 links and direct distribution information to the granule results page
When the links are supplied along with data links, they are displayed in tabbed interface. S3 links are copied to the clipboard, rather than being navigated to directly.
Granule results list page
- **Collection to test with:** Any collection with direct distribution links and s3 links
1. Navigate to the granule results page for a collection with the correct metadata/granules
2. Confirm direct distribution information is displayed
3. Confirm S3 links are displayed in the list
=> EDSC-3146: Adding S3 links to the granule results page

static/src/js/components/CollectionResults/CollectionResultsListItem.js
When loading a collection result that included 3 different badge, like Map Imagery, Customizable and Short Name badges, the height was not being updated to account for the badges, cutting off the last badge
Adding `element.current` to the dependency array for the useEffect that watches for `windowWidth` changes ensures the `setSize` function is called once the ref is loaded
Collections Results List
With production data, search for `AE_Rain`. This should load two collections, the first of which displays the bug.
Ensure all badges are fully displayed without resizing the panel
=> EDSC-3051: Fixes CollectionResultsListItem height on page load

serverless/src/processTag/__tests__/handler.test.js, serverless/src/processTag/addTag.js, serverless/src/processTag/handler.js, static/src/js/components/AdvancedSearchModal/RegionSearchResults.js, static/src/js/components/AdvancedSearchModal/__tests__/AdvancedSearchForm.test.js, static/src/js/data/advancedSearchFields.js
Earthdata Search creates tag data in CMR and today it does so without knowledge of whether or not that data is the same data already in CMR. This PR adds an effort to check existing metadata and prevent retagging collections with data that matches existing data.
Before sending the request to CMR to write tag data, Earthdata Search now queries CMR to retrieve the current metadata that can be compared to the data looking to be sent. If the data matches the request will not be sent and a log will be written indicating that it is being skipped.
All tagging jobs that use `concept_id` as the search condition.
=> EDSC-3062: Prevents overwriting tags with the same data

serverless/src/processTag/__tests__/handler.test.js, serverless/src/processTag/handler.js
Some jobs send an empty searchCriteria to processTag and that wasn't being defaulted in the new method, I've defaulted that to an empty object and added a test to catch it in the future.
=> EDSC-3062: Check for empty searchCriteria

static/src/js/util/files/generateDownloadScript.js
Allow for more redirects when downloading granule data via the download script.
=> EDSC-2251: Updates max redirects to 5 in download script

jest.config.js, static/src/css/modules/_badge.scss, static/src/css/modules/modules.scss, static/src/css/vendor/bootstrap/_overrides.scss, static/src/js/actions/__tests__/focusedCollection.test.js, static/src/js/actions/__tests__/project.test.js, static/src/js/actions/focusedCollection.js, static/src/js/actions/project.js, static/src/js/components/AutocompleteDisplay/AutocompleteDisplay.scss, static/src/js/components/Button/Button.scss, static/src/js/components/CollectionDetails/CollectionDetailsBody.js, static/src/js/components/Panels/PanelGroup.js, static/src/js/components/Panels/PanelGroupHeader.js, static/src/js/components/Panels/PanelGroupHeader.scss, static/src/js/components/Panels/__tests__/PanelGroupHeader.test.js, static/src/js/components/SearchPanels/SearchPanels.js, static/src/js/components/SearchPanels/SearchPanels.scss, static/src/js/components/SearchPanels/__tests__/SearchPanels.test.js, static/src/js/components/SpatialDisplay/SpatialSelectionDropdown.js, static/src/js/components/SpatialDisplay/SpatialSelectionDropdown.scss, static/src/js/components/TemporalDisplay/TemporalDisplay.js, static/src/js/components/TemporalDisplay/TemporalSelectionDropdownToggle.js, static/src/js/reducers/collectionMetadata.js, static/src/js/util/__tests__/isCSDACollection.test.js, static/src/js/util/isCSDACollection.js
Adds messaging to the granule results page for CSDA collections
Added a badge and message to the top of the panel
Granule results page
- **Collection to test with:** C1240538039-CSDA
1. Log in to a EDL account with CSDA enabled
2. View the granules page
3. Confirm tag and message are displayed
=> EDSC-3141: Display message on granule results page for CSDA collections

cypress/integration/paths/search/search_spec.js, serverless/src/collectionSearch/handler.js, static.config.json, static/src/js/util/collections.js, static/src/js/util/request/__tests__/collectionRequest.test.js, static/src/js/util/request/collectionRequest.js
Use the new `cloud_hosted` CMR parameter to retrieve collections for the feature facet `Available from AWS Cloud` instead of using the tag
Collection search
Select the `Available from AWS Cloud` feature facet. Ensure collections are returned successfully. Inspect the network request to ensure `cloud_hosted` parameter is used and not `tag_key`
=> EDSC-3184: Use the cloud_hosted parameter for the cloud feature facet

static/src/js/components/GranuleResults/GranuleResultsItem.scss
Fixing space below granule items with browse imagery
Tweaked some css
Granule results list
- **Collection to test with:** C1233200839-LPCLOUDUAT
1. Confirm no space below the start and end times on a granule item
=> EDSC-3174: Fixing space below granule items with browse imagery

static/src/js/App.js, static/src/js/components/ProjectPanels/ProjectPanels.js, static/src/js/components/ProjectPanels/__tests__/ProjectPanels.test.js, static/src/js/containers/ProjectPanelsContainer/ProjectPanelsContainer.js, static/src/js/containers/ProjectPanelsContainer/__tests__/ProjectPanelsContainer.test.js
Inform users about CSDA authentication on the project page
Display information about CSDA authentication the the edit options panel
Project page edit options panel
1. Visit `/projects?p=C1240538039-CSDA!C1240538039-CSDA&pg[1][v]=t&pg[1][gsk]=-start_date&q=CSDA&ac=true&tl=1623265263!3!!&m=-0.0703125!0.0703125!2!1!0!0%2C2`
2. Verify CSDA information is displayed on the edit options and granules panels
3. Confirm more details link opens CSDA modal
=> EDSC-3142: Displaying CSDA information on the project edit options panel

static/src/js/actions/__tests__/granules.test.js, static/src/js/actions/focusedCollection.js, static/src/js/actions/project.js, static/src/js/util/__tests__/getOpenSearchOsddLink.test.js, static/src/js/util/getOpenSearchLink.js, static/src/js/util/granules.js, static/src/js/util/request/__tests__/collectionRequest.test.js, static/src/js/util/request/collectionRequest.js
Retrieve the OpenSearch OSDD from the collection metadata, if the OSDD doesn't exist in the links, check the tags for the link
OpenSearch collections and granules
=> EDSC-3152: Retrieve the OpenSearch OSDD from the collection metadata

static/src/js/components/CollectionResults/CollectionResultsItem.scss
Fixing customizable badge spacing
Tweaked css to add spacing
Customizable badging on collection search results
- **Collection to test with:** N/A
1. Search for 'customizable' collections
2. Verify badges have spacing
=> EDSC-3203: Fixing customizable badge spacing

static/src/js/components/Preferences/PreferencesForm.js
Removes the unwanted box shadow on the preferences form.
Adding a `idPrefix` prevents the duplicate `#root` declaration and removes the unwanted styles.
Preferences form
- **Collection to test with:** N/A
1. Load preferences form
=> EDSC-3183: Removing box shadow on preferences form

bin/deploy-bamboo.sh, serverless-configs/aws-functions.yml, static.config.json, static/src/js/actions/__tests__/granules.test.js, static/src/js/actions/granules.js
Some collections have granules that have many links more than other collections. Currently those collections are pushing the upper limited of lambda response sizes. This change will allow us to easily configure the page_size parameter for fetching granule links in order to accommodate those larger collections
=> EDSC-3204: Makes the granule links page size configurable during deployment

static/src/js/App.js, static/src/js/components/OrderStatus/OrderStatus.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/OrderStatusItem.scss, static/src/js/components/OrderStatus/OrderStatusList.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/components/OrderStatus/__tests__/OrderStatusList.test.js, static/src/js/components/OrderStatus/__tests__/mocks.js, static/src/js/components/SearchPanels/SearchPanels.scss, static/src/js/containers/OrderStatusContainer/OrderStatusContainer.js, static/src/js/containers/OrderStatusContainer/__tests__/OrderStatusContainer.test.js
Display contextual messaging on the order status page when downloading a CSDA collection
Adds CSDA messaging to the order status page
Order status page
- **Collection to test with:** Any CSDA collection
1. Download a CSDA collection
2. Confirm contextual messaging appears on the order status page for the CSDA collection
=> EDSC-3143: Adds CSDA messaging to the order status page

static/src/js/util/__tests__/collections.test.js, static/src/js/util/collections.js
Quoted strings are now possible in CMR, but we don't want to add wildcard characters between words when a user provides a quoted string
=> EDSC-3178: Removes wildcard characters when a user enters a quoted string into keyword search

README.md, serverless/src/generateCollectionCapabilityTags/__tests__/handler.test.js, serverless/src/generateCollectionCapabilityTags/handler.js
Allows for running the collection capabilities tagging job on a single collection.
=> EDSC-3208: Fixes key to send to CMR when concept id is provided

static.config.json, static/src/js/actions/granules.js
Environment variables from deployments are parsed as strings, `granuleLinksPageSize` needs to be parsed as a integer in order to be passed as the `limit` param to GraphQL
=> EDSC-3204: Fixes limit type in graphql query

cypress/integration/map/map_spec.js, cypress/integration/paths/search/granules/collection_details/collection_details_spec.js, cypress/integration/paths/search/granules/granule_details/granule_details_spec.js, cypress/integration/paths/search/granules/granules_spec.js, cypress/integration/paths/search/search_spec.js, cypress/support/interceptUnauthenticatedCollections.js, static/src/js/util/collections.js
The `edsc.limited_collections` tag is used to limit the number of granules allowed per order for the collection. That tag was not being included in our collection metadata search
Include all edsc tags (`edsc.*`) when requesting collection metadata
This PROD collection should limit you to 2000 granules per order. Download buttons should be disabled if this collection contains more than 2000 granules. `C2052604735-LPDAAC_ECS`
=> EDSC-3223: Fixes limited collections

serverless/src/getAccessMethods/__tests__/handler.test.js, serverless/src/getAccessMethods/__tests__/supportsTemporalSubsetting.test.js, serverless/src/getAccessMethods/handler.js, serverless/src/getAccessMethods/supportsTemporalSubsetting.js, serverless/src/submitHarmonyOrder/__tests__/constructOrderPayload.test.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/constructOrderPayload.js, static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/EDSCAlert/EDSCAlert.js, static/src/js/components/EDSCAlert/__tests__/EDSCAlert.test.js, static/src/js/components/ProjectPanels/ProjectPanelSection.js, static/src/js/components/ProjectPanels/ProjectPanelSection.scss, static/src/js/components/ProjectPanels/__tests__/ProjectPanelSection.test.js, static/src/js/util/url/__tests__/projectCollections.test.js, static/src/js/util/url/collectionsEncoders.js
Allows a user to disable temporal subsetting for Harmony orders
Added a checkbox that disables temporal subsetting
Project page
- **Collection to test with:** C1234724470-POCLOUD
1. Add collection to project
2. Disable temporal subsetting
3. Confirm `time` parameter is not sent to Harmony and order is not subset
=> EDSC-3219: Allow user to disable temporal subsetting for Harmony orders

static/src/js/actions/__tests__/granules.test.js, static/src/js/actions/granules.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/OrderStatusItem.scss, static/src/js/components/OrderStatus/OrderStatusItem/DownloadFilesPanel.js, static/src/js/components/OrderStatus/OrderStatusItem/__tests__/DownloadFilesPanel.test.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/reducers/__tests__/granuleDownload.test.js, static/src/js/reducers/granuleDownload.js
This PR changes the granule downloads page from sending off parallel requests with `pageNum` to using CMR's scrolling requests to fetch the granule download links. It also adds a progress bar to the `DownloadFilesPanel` component to show the user their progress while waiting to fetch all the links.
=> EDSC-2460: Use CMR scrolling for granule download links

package-lock.json, serverless/src/getAccessMethods/__tests__/handler.test.js, serverless/src/getAccessMethods/handler.js, static/src/js/components/AccessMethod/AccessMethod.js
Fixes issue where, by default, a harmony order would not enable temporal subsetting
Sets the enableTemporalSubsetting property when the access method is created
Ordering data with a harmony access method
- **Collection to test with:** C1234724470-POCLOUD in UAT
1. Set a temporal bounds and order granules with collection C1234724470-POCLOUD
2. Confirm the project page defaults to enable temporal subsetting
3. Confirm output harmony granules are subset temporally
=> EDSC-3219: Enables temporal subsetting by default, updates package lock

static/src/js/util/request/__tests__/openSearchGranuleRequest.test.js, static/src/js/util/request/openSearchGranuleRequest.js
`fast-xml-parser` is parsing the OpenSearchGranule search response and adding an extra value to the end of the `entry` array, which is being returned as an empty string instead of an object. This fix accounts for that and removes the processing from that array item
I was not able to figure out why the xml parser is returning that data. As far as I could tell everything looks good in the XML
To replicate: https://search.earthdata.nasa.gov/search/granules?p=C1597990351-NOAA_NCEI&pg[0][v]=f&pg[0][gsk]=-start_date&q=C1597990351-NOAA_NCEI&tl=1629128131!3!!&m=-0.0703125!0!2!1!0!0%2C2
=> EDSC-3245: Fixes bug when XML is parsed with incorrect granule

static.config.json, static/src/js/components/OrderStatus/OrderStatus.js, static/src/js/util/files/__tests__/generateDownloadScript.test.js, static/src/js/util/files/generateDownloadScript.js
Updates the download script to work with CSDA data.
Added a check for isCSDA within the collection metadata, if its found and true we use the CSDA authentication endpoint over EDL.
Retrieval / Download of CSDA data.
=> EDSC-3201: Adds CSDA authentication to download script

static/src/js/components/CollectionDetails/CollectionDetailsBody.js, static/src/js/components/CollectionResults/CollectionResultsItem.js, static/src/js/components/CollectionResults/CollectionResultsItem.scss, static/src/js/components/CollectionResults/__tests__/CollectionResultsBody.test.js, static/src/js/components/CollectionResults/__tests__/CollectionResultsItem.test.js, static/src/js/components/CollectionResults/__tests__/CollectionResultsListItem.test.js, static/src/js/components/CollectionResults/__tests__/mocks.js, static/src/js/components/SearchPanels/SearchPanels.js, static/src/js/components/SearchPanels/__tests__/SearchPanels.test.js, static/src/js/util/__tests__/formatCollectionList.test.js, static/src/js/util/formatCollectionList.js
Displays additional consortiums on the search results and granule results lists where appropriate
Leverage messaging in place for CWIC collections, which can now be pulled from the consortiums array on the CMR JSON response
- Search results list item
- Granule results list header note
=> EDSC-3296: Display consortiums

cypress/integration/map/__mocks__/opensearch_granules/graphql.body.json, cypress/integration/map/map_spec.js, cypress/integration/paths/search/granules/collection_details/collection_details_spec.js, cypress/integration/paths/search/granules/granule_details/granule_details_spec.js, cypress/integration/paths/search/granules/granules_spec.js, static/src/js/util/request/__tests__/graphQlRequest.test.js, static/src/js/util/request/graphQlRequest.js
Added a missing `!` and tests for the graphQl request utility.
=> EDSC-3346: Ensures correct header is being sent

static/src/js/components/DeprecatedParameterModal/DeprecatedParameterModal.js
Adds external link styling to wiki link in modal
Add external link styling to wiki link in modal
Deprecated parameter modal
- **Collection to test with:** N/A
=> EDSC-3361: Adds external link styling to wiki link in modal

serverless/src/conceptMetadata/__tests__/handler.test.js, serverless/src/conceptMetadata/handler.js
Removes EDL client id from JWT token to work around CMR bug.
=> EDSC-3398: Removes EDL client id from JWT token

serverless/src/exportSearch/__tests__/handler.test.js, serverless/src/exportSearch/__tests__/jsonToCsv.test.js, serverless/src/exportSearch/jsonToCsv.js
Platforms values are returned from GraphQL as an array of objects, not as an array of short name strings. This PR adjusts the `jsonToCSV.js` code to account for that difference.
=> EDSC-3483: Fixes platforms values in collections CSV export

portals/amd/config.json, portals/soos/config.json, portals/standardproducts/config.json, static/src/js/actions/__tests__/portals.test.js, static/src/js/actions/portals.js, static/src/js/components/Banner/Banner.js, static/src/js/components/Banner/__tests__/Banner.test.js, static/src/js/components/SearchPanels/SearchPanels.js, static/src/js/util/__tests__/queryToHumanizedList.test.js, static/src/js/util/queryToHumanizedList.js
Some of the portals that use the `tagKey` parameter were using a string parameter and not an array of strings. This was causing some of the new subscriptions code to error when performing `.filter(` on that parameter.
Use lodash `castArray` to ensure that `tagKey` is always an array.
Updated the portal configs to use the correct array type parameter.
Ensured that any portals that do not have authentication enabled do not load the `SubscriptionsBodyContainer`
The following portals will error when logged in:
Antarctic Metadata Directory (AMD) (portal/amd)
Southern Ocean Observing System (portal/soos)
Standard Products (/portal/standardproducts)
Any environment
1. Login to EDSC with no portal applied
2. Visit the portal URL for one of the portals listed above
=> EDSC-3514: Updates portal configs to use correct tagKey parameter

static/src/js/components/CollectionDetails/RelatedUrlsModal.js
Fixes error page appearing when you click on "View all Related Urls"
Reverted body element to be a fragment instead of an array of elements, so it'll work with the rest of the code that processes it.
/search/granules/collection-details
1. go to /search
2. type in ASCAT
3. click on the first result
4. click on the kebab menu and click Collection Details
5. click view all related urls and the modal should appear now
Supersedes https://github.com/nasa/earthdata-search/pull/1532/files
=> EDSC-3518: Fix Related Urls Modal Error

static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/EchoForm.js, static/src/js/components/AccessMethod/__tests__/EchoForm.test.js, static/src/js/components/ProjectPanels/ProjectPanels.js, static/src/js/components/ProjectPanels/__tests__/ProjectPanels.test.js, static/src/js/containers/ProjectPanelsContainer/ProjectPanelsContainer.js
Some ECHO forms allow for temporal subsetting when a temporal constraint is applied to the user's search. This was not working when the user had only applied a granule level temporal constraint.
Previously we supplied temporal and overrideTemporal to the EchoForm component and it sorted out which should be passed to the echoforms plugin. This change moves that logic into ProjectPanels, and only passes a single temporal object through to EchoForm. It also looks for granule temporal and prefers that temporal over the global temporal and the overrideTemporal
ESI Access Methods with temporal subsetting.
Should work in any environment:
- Search for ATL22
- View granules for a collections with the customizable icons
- Apply a temporal filter within the granule filters
- Click Download All
- On …
=> EDSC-3513: Provides granule temporal to the EchoForm component when necessary

cypress/fixtures/shapefiles/antarctic.geojson, cypress/fixtures/shapefiles/arctic.geojson, cypress/integration/map/__mocks__/antarctic_shapefile_collections.body.json, cypress/integration/map/__mocks__/arctic_shapefile_collections.body.json, cypress/integration/map/map_spec.js, package.json, static/src/js/components/Map/ShapefileLayer.js, static/src/js/containers/MapContainer/MapContainer.js, static/src/js/containers/ShapefileDropzoneContainer/ShapefileDropzoneContainer.js, static/src/js/containers/ShapefileDropzoneContainer/__tests__/ShapefileDropzoneContainer.test.js, static/src/js/util/url/__tests__/mapUrl.test.js, static/src/js/util/url/mapEncoders.js
Some shapefiles when they are supposed to wrap around poles are not drawing on EDSC correctly
The ogre website we use to convert shapefiles to geojson did not understand the projection correctly. Passing the targetSrs parameter ensures the geojson shape returned works on our map. Additionally, if all of the latitudes of the shape are > 45 or < -45, I change the map projection to our arctic or antarctic projection, to better show the shape
Shapefile searching
Upload the [antartica.zip](https://github.com/nasa/earthdata-search/files/9698566/antartica.zip) to EDSC. The shape outlines Antartica, and the map projection will change to EPSG:3031 to better show the shape
=> EDSC-2612: Fixes shapefiles wrapping around poles

bin/deploy-bamboo.sh, static.config.json, static/src/js/components/CollectionResults/CollectionResultsItem.js, static/src/js/components/CollectionResults/CollectionResultsList.js, static/src/js/components/CollectionResults/CollectionResultsListItem.js
Removes remaining A/B test code leaving the default experience for the collection search results layout, which contains both a thumbnail (where possible) and a text description
Deleted some code.
Collection search results
- **Environment for testing:** any
- **Collection to test with:** n/a
1. Load the collection search results
2. Confirm the search results look as expected; containing both a thumbnail (where possible) and a text description
=> EDSC-3547: Removing collections search results layout A/B test code

cypress/integration/paths/search/__mocks__/non_eosdis.body.json, cypress/integration/paths/search/granules/collection_details/collection_details_spec.js, cypress/integration/paths/search/granules/granules_spec.js, cypress/integration/paths/search/search_spec.js, static.config.json, static.webpack.config.dev.js, static/src/js/containers/SubscriptionsBodyContainer/__tests__/SubscriptionsBodyContainer.test.js, static/src/js/containers/UrlQueryContainer/UrlQueryContainer.js, static/src/js/routes/Search/Search.js, static/src/js/routes/Search/__tests__/Search.test.js, static/src/js/util/__tests__/humanizedQueryValueFormattingMap.test.js, static/src/js/util/__tests__/queryToHumanizedList.test.js, static/src/js/util/__tests__/subscriptions.test.js, static/src/js/util/collections.js, static/src/js/util/humanizedQueryValueFormattingMap.js, static/src/js/util/queryToHumanizedList.js, static/src/js/util/subscriptions.js, static/src/js/util/url/__tests__/onlyEosdisCollections.test.js, static/src/js/util/url/__tests__/url.mocks.js, static/src/js/util/url/booleanEncoders.js, static/src/js/util/url/url.js
This PR changes the behavior of the `Include only EOSDIS collections` checkbox to use the consortium parameter instead of the current behavior of tags
Collection Search
Check the `Include only EOSDIS collections` checkbox, verify the consortium parameter is sent with the collection request and not the tagKey
=> EDSC-3522: Moves `Include only EOSDIS collections` to use consortium instead of tags

serverless/src/edlAdminAuthorizer/__tests__/handler.test.js, serverless/src/edlAdminAuthorizer/handler.js, serverless/src/edlAuthorizer/handler.js, serverless/src/edlOptionalAuthorizer/handler.js, serverless/src/util/__tests__/downcaseKeys.test.js, serverless/src/util/downcaseKeys.js
Our code was expecting an `Authorization` header, but we started receiving an `authorization` header. To fix that issue we downcase the keys in the header object before destructing `authorization` out of the headers. This ensures the casing is always what we expect
All logged in actions
Log in to EDSC, ensure collection results are returned.
=> EDSC-3565: Downcase keys in authorizer lambdas to ensure Authorization header is read successfully

static/src/js/components/GranuleResults/GranuleResultsBody.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsBody.test.js
When loading a granule results page directly from the URL (or refreshing the page while viewing granule results), the Search Time value is displaying `NaNs`
Default the load time to 0. If loadTime is 0, display the spinner, as the values have not been loaded yet
Granule search results
View granule results for any collection. Refresh the page. As soon as the page loads ensure that the search time spinner is visible and not `NaN`
=> EDSC-2514: Display spinner for granule search time before values start loading

serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitCatalogRestOrder/handler.js
Some granules have a larger payload than others, and when an order has 2000 granules that can really add up. Lambda has problems with handling that much data, so we are switching that call to retrieve granules from CMR to cmr-graphql, in order to retrieve just the field we need.
Switch the call retrieving granules in the ESI order submission from CMR to cmr-graphql
ESI (Customize) orders
Submit an ESI order with at least 2000 granules, ensure all sub orders are submitted successfully
=> EDSC-3628: Use cmr-graphql to retrieve granule titles when submitting ESI orders

static/src/js/util/files/generateDownloadScript.js
Sometimes data providers will host their granules for direct download on static hosting solutions (sometimes cloud-based) that return a `200` or `301` fetches the status code of the first granule URL.  Previously the download script only supported 302 (`Found`).
Pass the app approval check if fetching the first granule returns a `200` or `301`.
added some additional conditions to the if statement checking the status code after curl makes the first request for a granule
This updates the direct download script and will enable users to download granules without error from more data providers.
summary: generate and run a download script for a granule that wasn't previously working 
steps
1. got the main page
2. search for C1996881752-POCLOUD
3. click on the one search result
4. add the first …
=> EDSC-2960: updated download script to support data served with 200 and 301 HTTP codes

serverless-configs/aws-functions.yml, serverless/src/requeueOrder/__tests__/handler.test.js, serverless/src/requeueOrder/handler.js, static/src/js/actions/admin/__tests__/retrievals.test.js, static/src/js/actions/admin/retrievals.js, static/src/js/actions/index.js, static/src/js/components/AdminRetrieval/AdminRetrieval.js, static/src/js/components/AdminRetrieval/__tests__/AdminRetrieval.test.js, static/src/js/components/AdminRetrievalDetails/AdminRetrievalDetails.js, static/src/js/components/AdminRetrievalDetails/__tests__/AdminRetrievalDetails.test.js, static/src/js/containers/AdminRetrievalContainer/AdminRetrievalContainer.js, static/src/js/containers/AdminRetrievalContainer/__tests__/AdminRetrievalContainer.test.js, static/src/js/util/request/admin/__tests__/retrievalRequest.test.js, static/src/js/util/request/admin/retrievalRequest.js
When submitting large orders it is possible that one or more of the sub-orders that EDSC creates will fail to be submitted. If this happens currently it is up to the user to figure out which granules from their large order they are missing, or try to submit the entire order again.
This PR adds a button to the admin retrieval page to requeue a single sub-order for processing.
Ordering
As an admin user, visit the /admin/retrievals page, and find a retrieval you created. Click on that retrieval to visit the retrieval page.
Click the "Requeue" button next to one of the sub-orders, you should receive emails as the order processes and completes.
This should work for ESI, ECHO Orders, and Harmony orders
=> EDSC-3652: Adds admin ability to requeue orders

migrations/1676323693507_update-selected-features-column.js
Previously the selected_features column was stored as a `text []` type. The updated version of knex from EDSC-3615 is unable to handle that field correctly, so this PR changes that column to a `jsonb` type.
Write a migration to change selected_features from `text []` to `jsonb`
Customize ordering with a shapefile
Upload any shapefile. 
Order a collection with ESI that allows you to spatial subset with a shapefile
Ensure the ESI request is submitted successfully.
=> EDSC-3660: Updates selected_features column in shapefiles table

static/src/js/App.js, static/src/js/components/SecondaryToolbar/SecondaryToolbar.js, static/src/js/routes/ContactInfo/ContactInfo.js, static/src/public/robots.txt
The Contact Information route should use a hypen instead of an underscore to match our the other routes. Fix #1541
Routes have been renamed
URL to access contact information
=> EDSC-3484: Fix /contact_info url

schemas/sitePreferencesSchema.json, serverless/src/openSearchGranuleSearch/__tests__/renderOpenSearchTemplate.test.js, static/src/js/components/SearchPanels/SearchPanels.js, static/src/js/components/SearchPanels/__tests__/SearchPanels.test.js
As a user, I'd like to sort collections by start date
New filter has been added (#1545)
Grid sorting
=> EDSC-3093: Sort collections by start date

static/src/js/actions/__tests__/project.test.js, static/src/js/actions/project.js
Occasionally the graphql call to load project collections returns before the call the retrieve the saved access configs. I'm not able to reproduce locally, but I also saw that a similar error is displayed when the call to retrieve the saved access config fails
`await` the call to retrieve the saved access configs, and default the saved access configs value to ensure access methods are still loaded without a successful saved access configs response
=> EDSC-3678: Ensure getProjectCollections waits for savedAccessConfigs

serverless/src/submitRetrieval/__tests__/handler.test.js, serverless/src/submitRetrieval/handler.js
This fixes a bug by adding the DelaySeconds definition to the sqs entries, instead of the `sendMessageBatch` call
=> EDSC-3611: Fixing issue with DelaySeconds

cypress/e2e/map/map.cy.js, package-lock.json, static/src/js/components/Map/GranuleGridLayer.js, static/src/js/components/Panels/PanelGroupHeader.js
When viewing a collection, and clicking on a granule to 'focus' the granule. Returning to the collection results list is not removing the focused granule from the map
When the granule layer is removed, specifically call remove on `_granuleFocusLayer` and `_granuleStickyLayer` if they exist
Map
View a collection with granules (C2105092163-LAADS is a good option). Click on a granule to focus it. Click 'Search Results' to return to the collection search results. Ensure the granule is no longer visible on the map
=> EDSC-3558: Removes focused granule when returning to collection results

cypress/e2e/map/map.cy.js, static/src/js/components/Map/GranuleGridLayerExtended.js
If a user pans the map after selecting a granule, that granule no longer looks selected on the map
If the current 'stickied' granule is the same as the focused granule when `setResults` is called in `GranuleGridLayerExtended.js`, then don't call `_onEdscStickygranule`. This ensures the 'stickied' granule remains visible
Map
View a collection with granules (C2105092163-LAADS is a good option). Click on a granule to select it. Pan and/or zoom the map and the granule will not become deselected. Clicking on the granule again, or clicking on an empty part of the map will deselect the granule.
=> EDSC-3559: Do not deselect a granule when panning the map

serverless/src/exportSearch/__tests__/handler.test.js, serverless/src/exportSearch/__tests__/jsonToCsv.test.js, serverless/src/exportSearch/handler.js, serverless/src/exportSearch/jsonToCsv.js, static/src/js/actions/exportSearch.js
Exporting collection search results has been using an incorrect parameter name (`platformH` instead of `platformsH`). It was also using deprecated parameters and deprecated fields.
Update the cmr-graphql query to use the correct parameters and field names for exporting collection search results.
Export collection search results
Export collection search results. Specifically export when the following parameters have been added to the search context:
* Platforms
* Latency
* "Include only EOSDIS collections"
=> EDSC-3630: Updates exportSearch cmr-graphql query to use correct fields

serverless/src/util/__tests__/createJwtToken.test.js, serverless/src/util/createJwtToken.js, static/src/js/components/ContactInfo/ContactInfo.js
The email address in ESI forms should be populated by the user's URS profile's email address, but that value isn't available on the project page.
Return the email_address in the JWT when a user logs in. This will ensure the email address is available on the project page.
Logging in/ESI forms
Load the project page with a collection that has a ESI service. Ensure your email address is populated in the form
=> EDSC-3713: Return urs email address in jwt in order to populate echo forms

static/src/js/util/__tests__/retrievals.test.js, static/src/js/util/retrievals.js
With the changes in EDSC-3611, specifically to return orderOptions in the getProjectCollections cmr-graphql request, they payload we send when submitting a retrieval has gotten too large.
We save collection metadata and access methods when submitting a new retrieval. This PR removes the bulk of that metadata, and only sends the fields which are used to submit or to view retrievals
Retrievals
Submit retrievals of every kind, ensure successful sending and viewing of those retrievals
=> EDSC-3739: Removes unnecessary data from submitRetrieval payload

static/src/js/actions/__tests__/shapefiles.test.js, static/src/js/actions/shapefiles.js, static/src/js/components/Map/ShapefileLayer.js, static/src/js/components/SpatialSelection/SpatialSelection.js, static/src/js/reducers/__tests__/shapefile.test.js, static/src/js/reducers/shapefile.js
Refreshing the page, or visiting a new page like the project page when a shapefile is loaded and many shapes are selected is causing duplicate requests to be sent to CMR for collections and granules. Also multiple requests are being made to retrieve the shapefile from our database.
* Check the isLoading property for the shapefile in the redux store. Don't call onFetchShapefile if the file is already loading. This fixes the multiple calls to retrieve the shapefile
* As each selected shape's constraints are added to the query in SpatialSelection, check to make sure the query is actually going to change before calling onChangeQuery. This fixes the duplicate calls to collections, which in turn removes the duplicate calls to granules
Shapefiles
Load a shapefile with many shapes.
Select a few …
=> EDSC-3743: Avoid sending duplicate requests to CMR when multiple shapes are selected in a shapefile

static/src/js/components/Map/ShapefileLayer.js, static/src/js/reducers/__tests__/autocomplete.test.js, static/src/js/reducers/__tests__/collectionMetadata.test.js, static/src/js/reducers/__tests__/facetsParams.test.js, static/src/js/reducers/__tests__/map.test.js, static/src/js/reducers/__tests__/project.test.js, static/src/js/reducers/__tests__/query.test.js, static/src/js/reducers/__tests__/shapefile.test.js, static/src/js/reducers/__tests__/timeline.test.js, static/src/js/reducers/__tests__/ui.test.js, static/src/js/reducers/autocomplete.js, static/src/js/reducers/collectionMetadata.js, static/src/js/reducers/facetsParams.js, static/src/js/reducers/map.js, static/src/js/reducers/project.js, static/src/js/reducers/query.js, static/src/js/reducers/shapefile.js, static/src/js/reducers/timeline.js, static/src/js/reducers/ui.js
When clicking the Earthdata Search title, shapefiles were not getting removed from the map, and project collections were not being removed from the store.
Adjust the RESTORE_FROM_URL action types in the reducers to inherit from the reducer's initial state, rather than the current state. This was necessary in the shapefile and project reducer, but I adjusted all the reducers that matched that pattern to be consistent
Shapefiles, projects
Add a shapefile to the map, and add a collection to your project.
Click on the EDSC title
Ensure the shapefile is no longer on the map, or the spatial display
Ensure the "My Project" button in the secondary toolbar is no longer displayed
=> EDSC-3746: Reset shapefile and project status when calling RESTORE_FROM_URL

cypress/e2e/timeline/timeline.cy.js, jest.config.js, static/src/js/components/PortalBrowserModal/PortalList.js, static/src/js/components/PortalBrowserModal/PortalList.scss, static/src/js/components/PortalBrowserModal/__tests__/PortalList.test.js, static/src/js/components/SearchSidebar/SearchSidebarHeader.js, static/src/js/components/SearchSidebar/SearchSidebarHeader.scss, static/src/js/components/SearchSidebar/__tests__/SearchSidebarHeader.test.js, static/src/js/components/Spinner/Spinner.js, static/src/js/hooks/__tests__/usePortalLogo.test.js, static/src/js/hooks/usePortalLogo.js, static/src/js/util/jest/fileTransformer.js
Changes how we are importing portal logos and adds loading spinners while the thumbnails are loading.
- `usePortalLogo` was changed to improve handing of `import`s by caching previously imported paths
- `SearchSidebarHeader` was changed to display a spinner
- `PortalList` items was changed to display a spinner
- `usePortalLogo`
- `SearchSidebarHeader`
-  `PortalList`
- **Collection to test with:** Any
1. Load the portal modal
2. Load a portal directly
=> EDSC-3741: Adding loading spinners and tweaking usePortalLogo hook

static.webpack.config.common.js, static.webpack.config.dev.js, static.webpack.config.prod.js
Fixes duplicate css.
Removes a misconfiguration of the `MiniCssExtractPlugin`.
Production builds
- **Collection to test with:** n/a
1. Load SIT with the old CSS deployed
2. Load SIT with new CSS deployed
[ ] Verify the new CSS loads
=> EDSC-3742: Fixes duplicate css

static/src/js/components/CollectionResults/CollectionResultsList.js, static/src/js/components/EDSCTable/EDSCTable.js, static/src/js/components/GranuleImage/GranuleImage.js, static/src/js/components/GranuleImage/__tests__/GranuleImage.test.js
Convert class components to functional components (GranuleImage)
Changed the class component to use functional components and changed the accompanying test to use
react-testing-library instead of enzyme
Granule images
Select a collection that has images
select a granule and see if the granule image component comes up
ensure that the open and close functionality is working
ensure that loading dots appear if you try to switch between granules and ensure that these
load correctly
=> EDSC-3598: Convert class components to functional components (GranuleImage)

static/src/js/components/Errors/NotFound.js, static/src/js/components/Errors/__tests__/NotFound.test.js, static/src/js/containers/AuthCallbackContainer/AuthCallbackContainer.js, static/src/js/containers/AuthCallbackContainer/__tests__/AuthCallbackContainer.test.js, static/src/js/containers/AuthTokenContainer/AuthTokenContainer.js, static/src/js/containers/AuthTokenContainer/__tests__/AuthTokenContainer.test.js
AuthCallbackContainer, AuthTokenContainer, and NotFound are all class components that use the React UNSAFE_componentWillMount() method. They can be converted to functional components using the useEffect hook instead.
Replaced UNSAFE_componentWillMount() with useEffect, replaced the use of Enzyme testing library with React testing library, added a test for the NotFound component.
EDL authentication process and Earthdata Search 404 page.
To test AuthCallbackContainer and AuthTokenContainer locally:
1. Go to Earthdata Search.
2. Click on the "Earthdata Login" button at the top right and verify that you're at the same page you were on before the authentication page appeared.
3. I'm not really sure how to test that AuthTokenContainer works individually, but when it doesn't work, the …
=> EDSC-3596: Convert AuthCallbackContainer AuthTokenContainer and NotFound components to functional components.

static/src/js/components/ProjectCollections/ProjectHeader.js
Heather found while testing in UAT that EDSC-3599 created a bug where pressing Enter while editing a project name after the Download Data button loaded would take a user to the download page instead of submitting their new project name. 
While writing EDSC-3599, I replaced the code that triggered the project name submission upon pressing Enter with onKeyUp (from the original onKeyPress) because I heard that onKeyPress was being deprecated. To fix the Enter bug, I used onKeyDown instead of onKeyUp.
This bug fix impacts users who are trying to edit their project name from the keyboard instead of pressing the submit button.
1. Go to Earthdata-Search and add granules to a project.
2. Go to the project and attempt to change the project name.
3. Verify that pressing the Enter button while …
=> EDSC-3794: Fix ProjectHeader enter bug.

.github/workflows/ci.yml, bin/deploy-bamboo.sh, serverless.yml, serverless/src/edlAuthorizer/handler.js, serverless/src/retrieveGranuleLinks/__tests__/fetchCmrLinks.test.js, serverless/src/retrieveGranuleLinks/__tests__/fetchOpendapLinks.test.js, serverless/src/retrieveGranuleLinks/__tests__/handler.test.js, serverless/src/retrieveGranuleLinks/fetchCmrLinks.js, serverless/src/retrieveGranuleLinks/flattenGranuleLinks.js, serverless/src/retrieveGranuleLinks/handler.js, static.config.json, static/src/js/actions/granules.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/components/TextWindowActions/TextWindowActions.js, static/src/js/util/accessMethods/__tests__/buildAccessMethods.test.js, static/src/js/util/accessMethods/buildAccessMethods.js
In AWS, multiValueQueryStringParameters are not working as they do locally. This is causing no links to be returned. 
The CI workflow is also not waiting for playwright tests to pass before moving to the deploy step.
Change linkTypes from an array, or repeated parameter, to a comma delimited string of values.
Update ci.yml
Viewing download links
=> EDSC-3761: Fixes query parameters used in AWS, and ci workflow

sharedUtils/__tests__/getOpenSearchOsddLink.test.js, sharedUtils/getOpenSearchOsddLink.js
When looking for an OpenSearch OSDD the code was expecting links and relatedUrls to default to an empty array. But when those values are provided by cmr-graphql, if they are missing they are returned as null.
Check for existence of those values before calling `.forEach()` on them
Viewing collections
This link should show granule results, not a red banner at the top of the screen. http://localhost:8080/search/granules?p=C2011599335-ASF&pg[0][v]=f&pg[0][gsk]=-start_date&q=C2011599335-ASF&tl=1690405258.454!3!!
=> EDSC-3852: Account for links and relatedUrls being null when looking for an OpenSearch OSDD

serverless/src/edlLogin/__tests__/handler.test.js, serverless/src/edlLogin/handler.js, static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/components/TextWindowActions/TextWindowActions.js, static/src/js/containers/AuthCallbackContainer/AuthCallbackContainer.js, static/src/js/containers/AuthCallbackContainer/__tests__/AuthCallbackContainer.test.js, static/src/js/containers/EarthdataDownloadRedirectContainer/EarthdataDownloadRedirectContainer.js, static/src/js/containers/EarthdataDownloadRedirectContainer/__tests__/EarthdataDownloadRedirectContainer.test.js
Earthdata Download needs to be able to send a user to EDL to accept a EULA, and then be returned to EDD, through an EDSC redirect. This adds that redirect capability.
EDD Downloads
You need a collection that is behind a EULA, and a user that has not accepted the EULA. Try to download the files through EDD and you will be redirected to EDL to accept the EULA, then to EDSC to the earthdata-download-redirect page to re-open EDD
=> EDD-10: Support EULA callback to EDD

cypress/e2e/paths/search/granules/granules.cy.js, package-lock.json, package.json
Semver needs to be updated to a newer version
Updating Semver and dependent modules to newer verisons
Node modules
1. Pull latest code
2. Verify locally that semver version updates doesn't generate any new errors
=> EDSC-3850: Bumping semver version

static/src/js/components/Facets/Facets.js, static/src/js/components/Facets/FacetsItem.js, static/src/js/components/Facets/__tests__/Facets.test.js
- Added a '?' to the end of the customizable and made it so when hovered over it gives more detailed information as a tooltip on what selecting the checkbox will do.
- Also updated the tests for Facets.js to use React Testing Framework instead of Enzyme.
Added a new prop to the FacetItem called description that when contains a string, the '?' icon will show up at the end of the checkbox with that description showing up on hover.
Just the Facets.js/FacetsItem.js.
1. go to /search.
2. Navigate to the Customizable checkbox and hover over the '?' icon at the end of it.
3. Ensure the popup shows up with the correct message.
=> EDSC-3833: Improve Customizable facet messaging

bin/deploy-bamboo.sh, serverless.yml, serverless/src/submitRetrieval/__tests__/handler.test.js, serverless/src/submitRetrieval/handler.js
Access-control has problems with processing very large amounts of granule permissions within the AWS lambda timeout.
We can blunt the impact on access-control processing times by avoiding overloading the app with everything all at once.  I've added an environment var ORDER_DELAY_SECONDS which will be added to the queue delay for each page of the total order. 
Order payload insertion into SQS.
- UAT, large orders of SMAP granules with large metadata sizes
- I tested with C1236624098-NSIDC_TS1
1. Order many granules
2. Monitor logs for cmr-ordering, to verify granule permission calls to access-control are batching and completing
3. Monitor access-control logs to verify permission calls are completing fast enough
4. Order completes successfully.
=> CMR-9266: 2000 granule get-permission call taking too long

static/src/js/components/OrderStatus/OrderStatusItem.js, static/src/js/components/OrderStatus/OrderStatusItem/DownloadFilesPanel.js, static/src/js/components/OrderStatus/OrderStatusItem/__tests__/DownloadFilesPanel.test.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/components/TextWindowActions/TextWindowActions.js, static/src/js/components/TextWindowActions/__tests__/TextWindowActions.test.js
CSDA collections have their own authentication that makes using EDD impossible
We disable the EDD button on the download files panel when dealing with CSDA collections
The order status page after the order has been submitted
Try to order granules from a CSDA collection, verify EDD button doesn't exist on the download files panel.
=> EDSC-3876 disables edd button for csda collections

static/src/js/components/Map/GranuleGridLayerExtended.js, static/src/js/components/Map/__tests__/GranuleGridLayerExtended.test.js
When switching between a focused collection with map imagery, back to the collection search results, and then back into the same collection, the map imagery is not being displayed for the focused collection.
The projection check for map imagery was failing because the projection was not passed in to `setResults` in `GranuleGridLayerExtended`, when being called from `loadResults`. Adding `projection` keeps the value from being set to undefined, and the imagery is loaded as expected.
Map imagery
In SIT, search for `C1200269573-E2E_18_3` (or any collection with map imagery will work)
Click into the collection to view granules and map imagery, ensure that the map imagery loads. 
Click `Search Results` to go back to the collection results.
Click back into the collection again to view granules …
=> EDSC-3861: Fixes bug when viewing a focused collection's map imagery

static/src/css/modules/_tooltip.scss, static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/CollectionResults/CollectionResultsItem.js, static/src/js/components/CollectionResults/CollectionResultsItem.scss, static/src/js/components/FormFields/AccessMethodRadio/AccessMethodRadio.js, static/src/js/components/FormFields/AccessMethodRadio/AccessMethodRadio.scss, static/src/js/components/FormFields/AccessMethodRadio/__tests__/AccessMethodRadio.test.js
Moving the service name for `Harmony` customizable collection to the customize panel so user does not need to click on the `More Info` box. Rewriting tests that were using `Enzyme` to `react-testing-library`
Small change to render the service name on the customizable option instead of under the `More Info` block
1. Find a collection with `customizable` harmony service. Add the collection to your project go to the project page and hit customize
=> EDSC-3835: Display the Harmony service name more prominantly on the access methods list

static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/FormFields/RadioList/RadioList.js
Fixed up the issue the @macrouch brought up.
Send to RadioList an array of the objects and a function to render the Radio component and then call them in RadioList.
UAT
MetOp-C ASCAT Level 2 25.0km Ocean Surface Wind Vectors in Full Orbit Swath
1. type in _MetOp-C ASCAT Level 2 25.0km Ocean Surface Wind Vectors in Full Orbit Swath_ into the search bar
2. press enter and click on the first granule that loads
3. click download all
4. click on the different Radio Buttons and ensure everything renders as expected.
=> EDSC-3601: Fixed up Children usage in RadioList.js

serverless-configs/aws-functions.yml, serverless/src/eddLogger/__tests__/handler.test.js, serverless/src/eddLogger/handler.js
Adding a Lambda that will export log messages to CloudWatch sent from EDD.
EDSC
=> EDSC-3905: Create a Lambda to export logging in EDD to EDSC CloudWatch

README.md, static/src/js/components/TemporalDisplay/TemporalSelectionDropdown.js, static/src/js/containers/MapContainer/MapEvents.js, tests/e2e/map/map.spec.js
There is an issue on EDSC where if you switch from south polar to north polar projects or vice versa the webpage will no longer function. This is to correct that error by preventing the Arithmetic operation that causes this from occurring
Removing the function that is setting the center of the map. This value is being passed into leaflet's `setView` function. It seems to be holding onto the `lastCenter` field so when it tries to parse that value on the opposite polar projection it cannot find the coordinate. This is propagating as our web application crashing. We can remove this part of the code as it is not changing the view from what it is being set to when we already switch projections 
EDSC Map and projection switching
Switch from the south polar projection to the north polar …
=> EDSC-3869: Fixing projection switching between Antarctic and Arctic

static/src/js/util/accessMethods/__tests__/buildAccessMethods.test.js, static/src/js/util/accessMethods/buildAccessMethods.js, static/src/js/util/accessMethods/getVariables.js
There was a user requested fix to showing the variables associated to the collection in a project utilizing `Harmony` or `OpenDap` services. In `EDSC-3817` a change was made to include only variables associated to the services of a collection. Instead this ticket updates this business logic to show the variables associated directly to the collection **unless** there exists variables associated to a service of the collection.
Tweak business logic in modules for building the access method component
Access methods
Add a collection to your project which implements `opendap` and or `harmony` services. Ensure that on the variables page (select `Edit Variables` on the Configure data customization options) we get a view of all of the variables associated to that collection if there exists no …
=> EDSC-3909: Fix showing direct collection -> variable associations

static/src/js/util/request/__tests__/granuleRequest.test.js, static/src/js/util/request/granuleRequest.js
When EDSC retrieves granule metadata, we parse the links on each granule and look for one that is a browse type to use as the browse url (when a user clicks on the browse thumbnail). If that browse link is an s3 protocol link it doesn't work when clicking on it. 
Only look for links that start with `https://` to populate the browse link
Clicking on granule browse images
In UAT, the collection this was reported in is `C1259974840-ASF`, but I think they have fixed the metadata to ensure the https links come first, therefore get selected. I'm still trying to find an example of this in the wild to use for testing
=> EDSC-3900: Ensure browse image links are https links

serverless/src/submitHarmonyOrder/__tests__/constructOrderUrl.test.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/constructOrderUrl.js, static/src/js/util/__tests__/retrievals.test.js, static/src/js/util/createSpatialDisplay.js, static/src/js/util/retrievals.js
Bug fix for Harmony based orders handling variables
We add variables to the permittedAccessMethodFields so that it is available for the build url function farther down
We add variables to the permittedAccessMethodFields so that it is available for the build url function farther down
Harmony Orders completing correctly
The ticket includes example orders in uat and prod that can be re-ordered for testing.
=> EDSC-3819: Fixing `variables` object  in submitHarmonyOrder

static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/ProjectPanels/VariableTreePanel.js, static/src/js/components/Tree/Tree.js, static/src/js/util/accessMethods/__tests__/buildAccessMethods.test.js, static/src/js/util/accessMethods/buildAccessMethods.js, static/src/js/util/tree/TreeNode.js
Fixing an issue where selecting a service then selecting from the variables on that service the Tree panel is not updating so we are seeing the variables associated to another service. In the default case should be that the variables which appear are the variable directly associated to the collection in the project, however if the service has variables associated to it we want those to show up instead of the ones on the direct-collection association (even if they are just a subset of those)
Update the key prop in the render of the Tree component so that it has a reference to the `selectedAccessMethodServiceConceptId` such that when we change services this component is going to be re-rendered.
Project page and the variables tree view
Find a collection with different …
=> EDSC-3910: Switching between access methods is not updating the variables displayed

static/src/js/containers/AuthCallbackContainer/AuthCallbackContainer.js, static/src/js/containers/AuthCallbackContainer/__tests__/AuthCallbackContainer.test.js
Fix an issue on EDSC (Further info in the Teams file on this issue) this has been left purposefully vague
Altered parsing of redirect urls for strictness
Regression testing was done locally to ensure that we could still be redirected from EDD to URS and to the EULA page using the prod collection `C1214470488-ASF` with a profile that had not accepted any Eulas
We can check `C2202497474-LPCLOUD` collection to ensure that EDD redirects through URS are getting sent as expected
EDD redirects
EDL redirects
(Further info in the Teams file on this issue) this has been left purposefully vague
N/A
- [n/a] I have made corresponding changes to the documentation
=> EDSC-3930: Fixing issue on EDSC

static/src/js/components/Map/ShapefileLayer.js
When a geoJSON file is uploaded, EDSC would change to one of the polar basemaps if all of the coordinates were above 45° north or south. However, the polar basemaps don't actually extend that far towards the equator, so the uploaded shape is in an unexpected location over a black background. Users also wouldn't expect the basemap to change unless the region of interest is much closer to the poles.
This fix updates the latitude check to 66.5°, the approximate latitude of the Arctic and Antarctic Circles.
Display of uploaded geospatial files. 
1. Download [georgia_straight_vancouver.geojson.zip](https://github.com/nasa/earthdata-search/files/13746212/georgia_straight_vancouver.geojson.zip)
2. Unzip the file
3. Click the upload file button as shown:
4. Upload the unzipped geoJSON file
5. …
=> EDSC-3884: Set latitude check to Ant/arctic circle

static/src/js/components/Timeline/Timeline.js, static/src/js/components/Timeline/__tests__/Timeline.test.js
Fixing the Timeline display to show the temporal window of the focused collection.
Updating the Timeline component to reflect the focused collection temporal window while still saving the position of collections added to the project on the timeline.
EDSC
1. Select a collection with a temporal window.
2. Verify that the timeline reflects the temporal window for the focused collection.
3. Add the collection to the project.
4. Reproduce steps 2-3 for two other collections.
5. Go to "My Project" and verify that the colors on the timeline match the colors on the project panel.
=> EDSC-3981: Fixing Timeline display for focused collection

static.config.json, static/src/js/components/SpatialDisplay/SpatialSelectionDropdown.js, static/src/js/components/SpatialDisplay/__tests__/SpatialSelectionDropdown.test.js, static/src/js/containers/AuthRequiredContainer/AuthRequiredContainer.js, static/src/js/containers/AuthRequiredContainer/__tests__/AuthRequiredContainer.test.js, static/src/js/containers/ErrorBannerContainer/ErrorBannerContainer.js, static/src/js/containers/ErrorBannerContainer/__tests__/ErrorBannerContainer.test.js, static/src/js/containers/SecondaryToolbarContainer/SecondaryToolbarContainer.js, static/src/js/containers/SecondaryToolbarContainer/__tests__/SecondaryToolbarContainer.test.js, static/src/js/util/accessMethods/__tests__/buildAccessMethods.test.js, static/src/js/util/accessMethods/buildAccessMethods.js
The existing feature toggle needs to be a string otherwise it is getting parsed as truthy. We must update the feature toggles to be strings
Update those feature toggles to be string values instead of booleans so that the value that bamboo passes can get parsed with the correct logic
ordering for the order feature toggle and all database interactions as this disabled the secondary toolbar
Set the toggles for the database toggle and set the toggle for cmr-ordering and the database related rendered components in your `override.static.config.json` file
Ensure your database is either deleted or otherwise turned off I did so using: `pg_ctl -D /usr/local/var/postgresql@14 stop`
To test colormaps toggle against prod locally use: `C1996881146-POCLOUD`
To test cmr-ordering toggle against prod …
=> EDSC-3971: Update feature toggles to be string for bamboo vars

serverless-configs/aws-infrastructure-resources.yml
browse-scaler is moving to the EDSC aws account and will be rewritten as a lambda, we need to provide the redis infrastructure utilized by browse scaler
Updated the infrastructure serverless yml file to include new redis resources.
N/A
Run EDSC deployment and confirm resources are deployed properly
=> EDSC-3935 adds redis cache infra for browse-scaler lambda

static/src/js/components/AccessMethod/AccessMethod.js, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/ProjectPanels/VariableTreePanel.js, static/src/js/components/ProjectPanels/VariableTreePanel.scss, static/src/js/components/ProjectPanels/__tests__/VariableTreePanel.test.js, static/src/js/components/Tree/TreeItem.js, static/src/js/components/Tree/TreeItem.scss
Currently, the variables section of the customization form displays empty content when no variables exist. This is confusing UX. We should hide the variables section when no variables exist. The new behavior is to hide the `Edit Variables` button and display text letting the user know that there are no variables to edit for the selected service.
There was also a minor visual bug where the variables would display double, which was confusing to look at. This has also been rectified.
Project panel
1. Add a collection with variables associated to a service to your project.
2. Repeat for a collection without any variables.
3. Go to project panel page, and select `Edit Options` for a collection with a service that has variables associated.
4. Verify that the `Variables` panel displays as …
=> EDSC-3904: Improving edge cases for variable selection form

serverless-configs/aws-infrastructure-resources.yml
This is the cloud-formation changes needed to encrypt the database per the DAR requirements. We found for ordering we needed to update this to `14.10`. In actuality EDSC is already on `14.10` in the deployed environment because we allow minor version updates to take place, however, since this will destroy the old RDS and create a new one, the version specified must be available to AWS at the time of deployment which `14.4` was no longer. 
Update serverless inf to encrypt the RDS instance and a minor version update to the database engine
The database infrastructure
Ensure that when this is deployed the `Encrypted` property in the configuration of the RDS is set to true. In this ticket we also go through the necessary alerting and backing up workflow required to do this …
=> EDSC-3967: Encrypt the RDS and update Engine Version

serverless-configs/aws-infrastructure-resources.yml
Creates the new encrypted database. In this PR we will create a new RDS instance with the properties that we need (Encryption + engine version). In a subsequent PR we will delete the old database after we have filled in this new RDS with the data from the old one. This is needed because the `serverless` `cloudformation` template requires a reference to the old database for a variable in the `serverless.yml ` stack. So the `encryption enabled` property alone causes us problems. Instead by spinning up this new one there is no destructive action taken.
Added new encrypted RDS instance
Infrastructure
Ensure the new RDS instance has been created on AWS console and it is encrypted
=> EDSC-3967: First add new Encrypted database

README.md, serverless-configs/aws-infrastructure-resources.yml, serverless.yml, serverless/src/util/database/__tests__/getDbConnectionConfig.test.js, serverless/src/util/database/getDbConnectionConfig.js, static.config.json
Cloud-formation issue because `serverless.yml` is trying to pull in a reference to the `infrastructure` as we are trying to update the value. Using an updated variable
Add an updated variable for the new database and use that instead of overriding the value of the original one
Infrastructure 
Ensure a new database is created which is encrypted and the version specified
1. Step 1
2. Step 2...
=> EDSC-3967: Updating exported reference to the database endpoint and port

serverless/src/retrieveGranuleLinks/__tests__/fetchCmrLinks.test.js, serverless/src/retrieveGranuleLinks/fetchCmrLinks.js
Fixes granule_links look up to properly filter granules
Passing along the granule query params to the fetchLinks call was recently removed, adding it back
Download Panels
- PROD
- C2324689816-LPCLOUD
1. Order granules Direct Download with some temporal fitlering
2. Download Panels should show more granules than filtered for
=> EDSC-4006 adds granule query params back into fetchCmrLinks

serverless-configs/aws-infrastructure-resources.yml
Fix a discrepancy between the secret pointing to the old database and instead point to the new one (we cannot simply update the values in the Database because the username is not editable after creation)
Update the value of the secret manager so that it will point to the new database remove the newly created secret which was not being used
1. Step 1
2. Step 2...
=> EDSC-3967: Update the dbSecret to reference the new database

serverless-configs/aws-infrastructure-resources.yml, serverless.yml
This step is needed as its own deployment because the first deployment work needed to spin up the new encrypted RDS and move the references in the source code to using the new database properties which was failing to deploy in bamboo because the references could not be updated or deleted. This serves to 'clean up'  the old variables and infrastructure which is no longer being used
We fix some naming inconsistency from the previous commit, update the secret password for the encrypted database to be the correct value, and the main purpose which is to remove the old database infrastructure which is no longer getting written to
Infrastructure
When this completes we will have only a single database that is encrypted in SIT and all references in the source code will be …
=> EDSC-3967: Second remove the old UnEncryptedDatabase

static/src/js/components/SpatialDisplay/SpatialDisplay.js, static/src/js/components/SpatialDisplay/__tests__/SpatialDisplay.test.js, static/src/js/components/SpatialSelection/SpatialSelection.js
Minor update so that if a user does not commit to creating a `shapefile` and instead hits remove for rectangular and circular subsetting the cursor for creating the shapefile is not maintained
Added an event emission so that the cursor is removed and the leaflet state is updated added referance to disable the polygon from the current toolbars, otherwise when the `eventEmitter.emit('map.drawCancel')` was called it was not removing it if the user had selected polygon subsetting and canceled
Shapefile subsetting when canceling (really when using the remove button before having made a shapefile) for circles and rectangles
Ensure that when you start trying to subset by rectangle or circle if you hit remove the cursor for the shapefile is no longer maintained
Please include relevant screenshots …
=> EDSC-3717: Fix shape searching cursor remaining if you cancel creating a shape

static/src/js/components/GranuleResults/GranuleDownloadButton.js, static/src/js/components/GranuleResults/__tests__/GranuleDownloadButton.test.js
This adds the granule download button to the components that are disabled when the `disableDatabaseComponents` feature toggle is on
Pull out the configuration value and disable the button if it is on
Granule downloads when the feature toggle to disable the database components is on
Override the value in your static.json config for `disableDatabaseComponents` set it equal to the string value 'true' then try to do a granule download (make sure that it is being disabled by the fact that this feature toggle is on not because there are too many granules) so filter down to 1 or 2 granules. In SIT will need to redeploy EDSC with the bamboo variables set to true
=> EDSC-4044: Add granule download button to the disabledDownloadComponents

.github/workflows/ci.yml
Github Actions has warnings that we need to get off node16. This PR updates the actions versions to actions that use node20.
=> EDSC-4041: Updates actions to use node20 actions

portals/obdaac/config.json
Ensure that OBDAAC portal users do have authentication enabled. It was decided that this was a desired change to the portal configuration
authentication is no longer being set to false, instead we are going to use the default (true) value see https://wiki.earthdata.nasa.gov/display/EDSC/Portal+Creation+Guide 
OBDAAC portal
Use the OBDAAC portal and ensure that you can log into EDSC and download multiple granules
=> EDSC-4060: Allow authentication on the OBDAAC portal

portals/idn/config.json, static/src/js/components/SearchSidebar/__tests__/SearchSidebarHeader.test.js, static/src/js/util/__tests__/portals.test.js
Updated IDN Portal config.json
Update moreInfoUrl link value (logo link) in the config file.
Changed moreInfoUrl link value (logo link) in the config file.
It was changed to the ceos.org IDN site: https://ceos.org/ourwork/workinggroups/wgiss/access/international-directory-network/
It impact the logo in the EDSC's IDN Seach Portal and the More Info... link in the EDSC portal selection pop.
- Create a local EDSC in my local environment on my computer. 
- Clicked on the "Browse Portals"
- Clicked on the IDN Portal box's "More Info" link.
-  Link goes to https://ceos.org/ourwork/workinggroups/wgiss/access/international-directory-network/
- Click on the IDN Portal box on the pop for "Browse Portals".
- Click on the CEOS logo image.
-  Link goes to …
=> IDN-105: Change link on IDN Portal's icon

package-lock.json, static/src/js/components/AdvancedSearchModal/RegionSearchForm.js, static/src/js/components/AdvancedSearchModal/__tests__/RegionSearchForm.test.js
Add information for SWORD on advance search.
Added an alert box with the information.
- Advanced search
- **Collection to test with:** None
1. Select the advanced search filter
2. select river reach
3. Observe the information is displayed
- [x ] I have performed a self-review of my own code
=> EDSC-4053: Add SWORD info on advance filter

serverless-configs/aws-infrastructure-resources.yml, serverless.yml
Fix the security rule for the elasti-cache instance so that it is accessible group from EC2 instance and from lambda add exported variables which can be accessed by lambdas
The current setting for the redis-cache instance was not making it possible to connect to it via EC2 instance or lambdas. This is being used for the image rescaling lambda that will deprecate browse-scaler
Configuration for redis cache, adds variables accessible to lambdas for references to the cache 
Log into AWS or connect to it locally. connect to the EC2 instance and ensure that using `redis-cli6 ` can connect to the cache to view or del a key in SIT
=> EDSC-4084: Fix accessibility of the Redis Cache

static/src/js/util/accessMethods/__tests__/buildAccessMethods.test.js, static/src/js/util/accessMethods/buildAccessMethods.js
This fixes and issue due to an update in [graphql](https://github.com/nasa/cmr-graphql/commit/d393cb77b182b96acc90e69a6fa101616ccb1a85) where responses are now returning an empty array instead of null. Normally variables available for subsetting are those which are associated to the collection record itself, however, to support a use-case in `EDSC-3909` variables that can be subset are overwritten by the variables associated to the service record instead (if they exist). Due to the graphql change we are now also ensuring that there are variable records not just that the response object exists
Update logic for overwriting variables off of the UMM-S record
Variable subsetting
1) Ensure that the tempo collection in UAT C1254854453-LARC_CLOUD has selectable variables which are those …
=> EDSC-4101: Add check to ensure size of service associated variables is not empty

README.md, cypress/e2e/panels/panels_behavior.cy.js, static/src/css/_layout.scss, static/src/js/App.js, static/src/js/__tests__/App.test.js, static/src/js/components/DownloadHistory/DownloadHistory.js, static/src/js/routes/ContactInfo/ContactInfo.js, static/src/js/routes/Downloads/Downloads.js, static/src/js/routes/EarthdataDownloadRedirect/EarthdataDownloadRedirect.js, static/src/js/routes/Preferences/Preferences.js, static/src/js/routes/Project/Project.js, static/src/js/routes/Project/__tests__/Project.test.js, static/src/js/routes/Search/Search.js, static/src/js/routes/Subscriptions/Subscriptions.js, tests/e2e/map/map.spec.js
Lazy load the `MapContainer.js` component 
Update the imports for `MapContainer.js` so that it is bundled separately, have the error-boundry use the `Spinner` with a new class for when the Map is loading. Updated Project component to be a functional component and rendering it the same way as the other routes are. Updated App.test.js for technical debt and to test that the Map is being loaded after being awaited. Updated the project.test.js route tests to RTL for tech debt. Updates class names which were not being used before to the correct ones, add a new `scss` modifier for the loading state
Search page, Projects page routes. Background color and scss for the other routes
1) Ensure that the map container is not getting reloaded. Go to a page that does not contain the map such as the …
=> EDSC-2673: Lazy load Leaflet

serverless/src/conceptMetadata/__tests__/handler.test.js, serverless/src/conceptMetadata/handler.js, static/src/js/components/SearchPanels/SearchPanels.js
Fixes an issue where while logged in the collection-details `View More Info` link was not properly working and instead returning a `500` error because it was unable to pass the token from user
Fixing the link to metadata preview by passing full header including the `Bearer` prefix for the token
Integration with metadata-preview the link for the collection-details
- **Environment for testing: Any**
- **Collection to test with: Any**
1. While logged in go to the collection details page
2. Ensure that the page's `View More Info` page correctly takes you to the metadata-preview page for the selected collection
Current issue:
localhost fix for a collection
=> EDSC-4116: Metadata Display link 'View More Info' returns 500 error

package-lock.json, package.json
Minor version bump for `serverless-finch` to keep up with changes
We discussed this at standup and though it does not resolve the `snyk` scan entirely due to the associated `vul` being brought in  by another package we decided to bump this version as its own ticket regardless
The IaC specifically the deployment of static-assets into our s3 bucket
Regression test to ensure that this is able to deploy correctly on CI/CD and that the static assets are present correctly on s3
=> EDSC-3993: Bump serverless-finch

static/src/js/components/ChunkedOrderModal/ChunkedOrderModal.js, static/src/js/components/ChunkedOrderModal/__tests__/ChunkedOrderModal.test.js, static/src/js/containers/EDSCModalContainer/EDSCModalContainer.js
User did not want to see the notice for the confirmation emails when the access method does not support that functionality (for instance with Harmony). Also rewrote the component as a functional component for our continuous effort towards updating our class based components
Rewrote the component into functional component minor changes to the `html` added a check for to include or not include the confirmation email paragraph
The `chunkedOrderModal` component
1) Find collections with `> 2,000`
2) Add Selected Access method for `ordering(echo-orders)`  or/and for `esi` `C2564427300-NSIDC_ECS`
or `C2750966856-NSIDC_ECS`
3) Ensure that when the modal for the chunked orders appear ensure that both of them have the notice for email confirmation
4) Repeat that with a service that does not have …
=> EDSC-4132: As a user, I'd like to not receive a message that I will be sent a confirmation email, if no confirmation email will be sent.

sharedUtils/__tests__/orderStatus.test.js, sharedUtils/orderStatus.js, static/src/js/components/OrderStatus/__tests__/OrderStatus.test.js
Adding a new state for Harmony orders `running_with_errors`. There were Harmony orders failing/going on indefinitely   because the status that Harmony was passing back was `running_with_errors` which the state machine was failing to transition from `in_progress` as a result the state went to `false` which caused errors.
By updating the enum list of `in_progress` we can ensure that the state machine is able to transition between `in_progress` to `running_with_errors` correctly (`running_with_errors`) will resolve to EDSC as `in_progress` but, the status is coming from Harmony and we were not mapping it correctly
AWS state machine for fetching the Harmony job status updates
- **Environment for testing: Prod**
- **Collection to test with: C2142776747-LPCLOUD**
Use a collection such as …
=> EDSC-4134: Harmony Order status not updating when harmony is progressing with errors

static/src/js/components/Sidebar/SidebarSection.scss
The granule datepicker was being partially hidden when the parent container did not have enough room. 
Removed `overflow: hidden;` from SidebarSection.scss
Granule temporal searches
http://localhost:8080/search/granules?p=C2069247359-GES_DISC
Ensure both start and end date picker are fully visible
=> EDSC-4139: Fixes granule datepicker being partially hidden

static/src/js/components/Datepicker/Datepicker.js, static/src/js/components/GranuleFilters/GranuleFiltersForm.js, static/src/js/components/GranuleFilters/__tests__/GranuleFiltersForm.test.js, static/src/js/components/TemporalDisplay/TemporalSelectionDropdown.js, static/src/js/components/TemporalDisplay/__tests__/TemporalSelectionDropdown.test.js, static/src/js/components/TemporalSelection/TemporalSelection.js, static/src/js/containers/DatepickerContainer/DatepickerContainer.js
EDSC-4129: When toggling recurring temporal on for granule temporal, the days of the year were not being set. So if you had already put the start and end date in before selecting Recurring, no days were set, resulting in the UI looking correct, but the wrong query being sent to CMR.
EDSC-4131: If one of the recurring start/end years was a leap year and the day was after 2/28, the day of the year was not comparable to the other year. For example, June 1 2023 is not the same day of the year as June 1 2024 (leap year). This fix was to always calculate the day of the year based off the start year of the recurring range
Recurring temporal, collection and granule level
EDSC-4129: 
From the collection level temporal:
select a start date
select an end date
then check the Recurring checkbox
If you …
=> EDSC-4129, EDSC-4131: Fixes temporal selection bugs

package-lock.json, package.json
- While we are not directly using `ws` keeping it updating is fixing vul issues on snyk
- It appears that having gone through the history that is likely why it was brought into the package.json in the first place see https://github.com/nasa/earthdata-search/commit/81410d0cb8639827392427b6f3fc58d1ea3563d1 for more information
Pulls `ws` back in so that we can resolve an upstream vul issue
Imports the npm package `ws` back into the project 
This should have no functional changes to the application nor the ci process other than the resolving package dependency issues which alert our snyk static code analyzer
- **Environment for testing:*Any*
- **Collection to test with:*Any*
Regression test EDSC and ensure that the vul is no longer being reported
Please include relevant screenshots or files …
=> EDSC-4145: Add `ws` back in to fix vul

.github/workflows/performance.yml, package.json, tests/e2e/performance/performance.spec.js
Adding some basic metrics for tracking in Playwright tests. LCP tracking and Time to Last Byte of the Search pages load time.
Added two playwright tests to capture the LCP and the response end time of the search page loading. This correlates to the time it takes to receive all javascript code.
No impact to the actual application.
Running the playwright tests will show allow for inspection of the metrics.
Search page metrics
LCP passing test.
=> EDSC-4055: Add performance testing

static/src/js/containers/DatepickerContainer/DatepickerContainer.jsx
Small bugfix the resolves auto completing datetime bugs.
changed the validation from moment.ISO_8601 to YYYY-MM-DDTHH:m:s.SSSZ
Date picker text inputs.
1. Go to all datetime inputs in earthdata search
2. Observe no unexpected autocompletion or any buggieness in the behavior
=> EDSC-3937: reverting how we validate datetimes so that we don't have unexpected bugs in the Vite feature.

bin/deploy-bamboo.sh
Fixes how the deployment env var is created.
Move the env var to the correct place in the static.config.json that is created by the bamboo deployment script
Deployment modifying default sort.
1. Modify the env var in the bamboo deployment.
2. Run deployment.
3. Verify the default sort value changes.
=> EDSC-3538: Make Relevancy the default sorting option on EDSC home page

static/src/js/components/OrderStatus/OrderStatusItem/BrowseLinksPanel.scss, static/src/js/components/OrderStatus/OrderStatusItem/DownloadFilesPanel.scss, static/src/js/components/OrderStatus/OrderStatusItem/DownloadScriptPanel.jsx, static/src/js/components/OrderStatus/OrderStatusItem/S3LinksPanel.jsx
Previous updates to the link styling included some regressions in the format of links on the download page. This addresses link formatting for four different panels of the download page.
- Direct download links no longer wrap
- S3 links no longer wrap and no longer have bullets
- Browse imagery links no longer wrap
- The margin on the bottom of the download script panel is slightly different
Download page
- `C1256568253-EEDTEST` in **UAT** is an example collection that has browse imagery
- `C1692982070-GES_DISC` in **PROD** is an example collection with S3 links
=> EDSC-4073: Fix link styling in downloads page

static/src/js/components/GranuleResults/GranuleResultsFocusedMeta.jsx, static/src/js/components/GranuleResults/__tests__/GranuleResultsFocusedMeta.test.js
Fixes an issue where we were displaying a smaller focused granule thumbnail image than intended
Changed the url parameters on the image request to a larger size
Focused granule thumbnail in the expanded view
- **Collection to test with:** C1262899924-LARC_CLOUD
This UAT url should focus the granule:
/search/granules?p=C1262899924-LARC_CLOUD&pg[0][v]=f&pg[0][id]=TEMPO_CLDO4_L2_V03_20240808T000113Z_S016G05.nc&pg[0][gsk]=-start_date&ee=uat&g=G1268712859-LARC_CLOUD&q=TEMPO_CLDO4_L2_V03&tl=1723642935!3!!&lat=39.3046875&long=-53.71875
1. Focus a granule
2. View the expanded granule thumbnail
3. Confirm a 538 x 538px image is displayed
=> EDSC-4217: Fixing focused granule thumbnail bug

package-lock.json
Fixes the following vulnerabilities identified in EDSC:
- Improper Verification of Cryptographic Signature
- Uncontrolled resource consumption
- Resource Exhaustion
- Regular Expression Denial of Service (ReDoS)
Upgraded the package versions for `elliptic`, `braces`, and `browserify-sign`. All of these are required by other packages that have not updated their dependencies to reference updated versions yet.
Then, I manually upgraded several AWS packages identified by `npm audit` so that we could identify which were resulting in the largest changes in `package-lock.json`. Finally, ran `npm audit fix` for the remaining packages.
Cryptography, brace expansion, AWS API clients via XML parsing library.
Do regression testing following the EDSC regression test …
=> EDSC-4228: upgrade packages with npm audit fix

static/src/js/actions/__tests__/project.test.js, static/src/js/actions/project.js
When a user is unauthorized, either because they are not logged in or otherwise, and they select granule filters and attempt to downloaded, upon redirect to the project page then subsequent redirect to EDL then again back to the project, the filters they had selected can be dropped.
When loading the project page, we now abort the process at the savedAccessConfigs request when a 401 is returned, instead of continuing down to the graphQl call after.  Having both requests being made and fail with 401 is what was ultimately causing the confusion with the redirects.
project page
In any environment,
1. Select some granules from download while not logged in.
2. Press the download button to progress to the project page.
3. Once redirected to EDL login, enter in credentials and submit (to be …
=> EDSC-4079: Subsetting Issue When Downloading Granules from Earthdata Search

static/src/js/actions/project.js, static/src/js/components/GranuleResults/GranuleDownloadButton.jsx, static/src/js/components/GranuleResults/GranuleResultsActions.jsx, static/src/js/components/GranuleResults/__tests__/GranuleDownloadButton.test.js, static/src/js/components/GranuleResults/__tests__/GranuleResultsActions.test.js, static/src/js/components/OrderStatus/OrderStatus.jsx, static/src/js/components/SearchPanels/SearchPanels.jsx, static/src/js/containers/GranuleResultsActionsContainer/GranuleResultsActionsContainer.jsx, static/src/js/containers/GranuleResultsActionsContainer/__tests__/GranuleResultsActionsContainer.test.js, static/src/js/util/__tests__/isLoggedIn.test.js, static/src/js/util/isLoggedIn.js
When a user is unauthorized, either because they are not logged in or otherwise, and they select granule filters and attempt to downloaded, upon redirect to the project page then subsequent redirect to EDL then again back to the project, the filters they had selected can be dropped.
Refactored the granule download button to send the user to a login page directly when they are trying to download granules while not logged in, instead of relying on failed subsequent calls on the project page that required authentication.
Granule download button.
In any environment,
1. Select some granules from download while not logged in.
2. Press the download button to progress to the project page.
3. Once redirected to EDL login, enter in credentials and submit (to be redirected back)
4. Verify your …
=> EDSC-4079: error status code check change

serverless.yml, static/src/js/components/GranuleFilters/GranuleFiltersForm.jsx, static/src/js/components/GranuleFilters/GranuleFiltersForm.scss, static/src/js/components/GranuleFilters/__tests__/GranuleFiltersForm.test.js, static/src/js/containers/GranuleFiltersContainer/__tests__/GranuleFiltersContainer.test.js
Improve the tool-tip access to further information on the 
Summarize what you changed.
Updates the contents and mechanism we inform the user about this granule filter. Adds tool-tip with precise language
Majority of code changes was technical debt reduction by rewriting the `static/src/js/components/GranuleFilters/__tests__/GranuleFiltersForm.test.js` and some minor cleanups to `static/src/js/containers/GranuleFiltersContainer/__tests__/GranuleFiltersContainer.test.js`
Updates the `serverless.yml` with setting for `esbuild` to ignore static and test files to improve performance in local development
- **Environment for testing:*Any*
- **Collection to test with:*Any*
1. On the Granules page for a selected collection hover over the Granule-Id tooltip on the form ensure …
=> EDSC-4240: Improve the granule filters tool-tips accessibility and content

static/src/js/components/EDSCImage/EDSCImage.jsx, static/src/js/components/EDSCImage/__tests__/EDSCImage.test.js, static/src/js/components/GranuleResults/GranuleResultsFocusedMeta.jsx, static/src/js/components/GranuleResults/GranuleResultsItem.jsx, static/src/js/components/GranuleResults/__tests__/GranuleResultsItem.test.js
In cases where the granules are `opensearch` they are not hosted on the CMR so the scaleImage lambda which attempts to fetch data from a CMR call is going to fail. Additionally the `id` value on the granule is actually a separate endpoint which is why we were seeing some `CORS` errors our `node-fetch` call was trying to go to the endpoint in the `id` 
Create clause to only fetch the image using the scaleImage lambda if the granule is not an opensearch granule
Granule Search result thumbnails for `opensearch` granules
- **Environment for testing:*Prod*
- **Collection to test with:*C3108204134-INPE*
1. Go to the http://localhost:8080/search/granules?portal=idn&p=C3108204134-INPE&pg[0][v]=f&pg[0][gsk]=-start_date&fdc=ESA%252FESRIN&fpj=FedEO&ac=true&tl=1719422073!3!!&lat=-8.477034055239216&lon …
=> EDSC-4199: Granule browse images are not appearing on EDSC (IDN Search Portal)

serverless-configs/aws-functions.yml, static/src/js/components/Map/GranuleGridLayerExtended.jsx, static/src/js/components/Map/__tests__/GranuleGridLayerExtended.test.js, static/src/js/components/Map/__tests__/mocks.js
1. Some collections are reported to be showing the same GIBS image for every granule.
2. Some collections that should have imagery are not showing any.
1. We are currently sending just the date to GIBS when requesting granule imagery. We need to be sending the full date time of the granule to retrieve the correct image for each granule
2. Our lambda has been running out of memory and not successfully creating the tags we use to trigger the request for granule imagery. Increasing that lambda memory will allow the function to finish execution.
Granule imagery
This collection was reported to show the same image for each granule. If you open your browser dev tools and look at the image request for the granule imagery, you should see the full date time, rather than just the date …
=> EDSC-4108: Sends full date time in GIBS request for imagery. Increases lambda memory for generating GIBS tags

serverless/src/generateGibsTags/__tests__/handler.test.js, serverless/src/generateGibsTags/__tests__/mocks.js, serverless/src/generateGibsTags/getSupportedGibsLayers.js, serverless/src/util/authorizer/__tests__/validateToken.test.js, serverless/src/util/authorizer/validateToken.js
When we parse the wv.json file to build our GIBS tags, we need to be processing 'granule' type layers the same way we do 'wmts' type layers.
I also made a change to validateToken to only request a single row from the database, an improvement over requesting many rows and only using the first row. We want to see if this improves performance issues we've been seeing in production.
GIBS tagging/imagery
To fully test this process we need to run the code in production, because the collection concept-ids are only found in production
=> EDSC-4108: Adds 'granule' type layers to GIBS tagging job

static/src/js/components/AccessMethod/AccessMethod.jsx, static/src/js/components/AccessMethod/__tests__/AccessMethod.test.js, static/src/js/components/FormFields/AccessMethodRadio/AccessMethodRadio.jsx
Taking a second look at and improving the tool tip for the harmony access method.
We added a link to the harmony landing page mainly, there are some mild adjustments to margin and link color as well.
AccessMethod and AccessMethodRadio
- **Environment for testing:** prod
- **Collection to test with:** C1996881146-POCLOUD
1. Select granules and progress to project page
2. Open up the access method component and mouse over/hover the ? icon to display the tooltip
Before:
After:
=> EDSC-4071: Improve the display of the Harmony tooltip

static/src/js/components/Datepicker/Datepicker.jsx, static/src/js/components/Datepicker/__tests__/Datepicker.test.js, static/src/js/components/GranuleFilters/GranuleFiltersForm.jsx, static/src/js/components/GranuleFilters/__tests__/GranuleFiltersForm.test.js, static/src/js/containers/DatepickerContainer/DatepickerContainer.jsx, static/src/js/containers/DatepickerContainer/__tests__/DatepickerContainer.test.js
Currently when you type into the granule filters temporal fields, every new keystroke results in a query to CMR. We want to limit sending those queries to only when the user has finished typing.
I passed a `shouldSubmit` flag into the `onSubmitStart` and `onSubmitEnd` callbacks in `GranuleFiltersForm`. This flag is false for regular change events, but true when the user clicked a date, or blurs the field.
I also don't submit the metrics call unless a query is submitted.
Granule Filters
Select a collection to view the granules, and the granule filters.
Selecting a date by clicking in the datepicker should always result in a new granules query sent to CMR.
Typing in the temporal fields should not send a granules query to CMR until you leave/blur the textbox.
=> EDSC-4218: Don't submit granule queries on each keystroke of temporal entry

bin/deploy-bamboo.sh
Adding env var for tour so that it can be turned off. This just pulls from bamboo env vars to do so
Adding new env var to the bamboo script
EDSC sit tour, edsc environment variables
1. Set env var in bamboo
2. Confirm that tour features can be toggled via redeployments
=> EDSC-4162: Add bamboo var for tour feature toggle

static/src/js/components/Map/GranuleGridLayerExtended.jsx
Screens with decimal DPR values (like 0.833) are drawing granule outlines in the wrong location and scale. See faint green lines at top left and top center, they should be around the orange granule imagery
Rounding up the DPR to the next round number seems to fix this issue
Granule outlines on the map
You can emulate the dpr with Chrome dev tools (Settings > Devices > Add custom device... > Provide a name, resolution, and Device pixel ratio. Then in your EDSC tab's dev tools click the button "Toggle device toolbar" (second button in the top left), then you will see a toolbar show up in your browser where you can select your newly created device. 
A known DPR causing this issue is `0.8333333134651184`, but any non whole number will cause the issue (e.g. 1.2)
Correct outlines
=> EDSC-3980: Fixes granule outlines for screens with decimal DPR values

static/src/js/components/Map/GranuleGridLayerExtended.jsx, static/src/js/components/Map/__tests__/GranuleGridLayerExtended.test.js
Our granule outlines will draw the latest granules above other granules. When you select a granule (from the results list or map) it will pull that granule to the 'top' by reordering the list of granules the map is processing. GIBS imagery does not behave in the same way, it is showing the oldest granules.
Reverse the list of granules passed into the function that renders the imagery.
Granules with GIBS imagery
I've found [this collection](http://localhost:8080/search/granules?p=C2930763263-LARC_CLOUD&pg[0][v]=f&pg[0][gsk]=-start_date&q=C2930763263-LARC_CLOUD&ot=2024-07-01T00%3A00%3A00.000Z%2C2024-07-31T23%3A59%3A59.999Z&tl=1728336950!3!!&lat=26.58553990490026&long=-220.78125&zoom=1) useful for testing this. 
Take care note of what the image displayed looks like (look for gaps in the …
=> EDSC-4294: Reverse granule imagery list to align with granule outlines

migrations/1730216056247_add-index-to-retrieval-orders.js, migrations/1730216091956_add-index-to-retrieval-collections.js
Adds two database indexes to improve database efficiency for queries to `retrieval_orders` and `retrieval_collections` tables.
Calls to the following lambdas will be impacted:
- retrieveGranuleLinks
- getRetrievals
- fetchRetrievalHistory
- getRetrieval
- getRetrievalCollection
Ensure submitting a retrieval and fetching download links works. 
Ensure viewing the download history page works
=> EDSC-4290: Adds database indexes to retrieval_orders and retrieval_collections

serverless.yml, static/src/js/App.jsx
Changing the configuration index file that is being stored in S3 from no-store to no-cache. "no-cache" allows caching but requires revalidation with the origin server before using the cached copy. Verified that caching behavior works as expected in SIT environment. Confirmed that updates to the configuration file are properly reflected after cache revalidation
=> EDSC-4257: Enable CloudFront caching in EDSC

serverless/src/submitCatalogRestOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/util/__tests__/processPartialShapefile.test.js, serverless/src/util/processPartialShapefile.js
Shapefile subsetting when the shapefile has a `selected_features` field is broken because the SQL statement to insert the data is invalid.
We need to stringify the `selected_features` array before inserting it into the database.
Shapefile subsetting (Harmony, ESI)
Upload a shapefile and submit a Harmony order for a collection that supports shapefile subsetting. In UAT `C1254854453-LARC_CLOUD` works.
Ensure that the order submits successfully to Harmony
=> EDSC-4296: Fixes inserting `selected_features` into shapefiles database table

serverless/src/submitHarmonyOrder/__tests__/constructOrderPayload.test.js, serverless/src/submitHarmonyOrder/__tests__/handler.test.js, serverless/src/submitHarmonyOrder/constructOrderPayload.js, serverless/src/submitHarmonyOrder/handler.js, serverless/src/util/database/getDbConnection.js
Adding two labels to Harmony orders in order for the Harmony team to track EDSC orders and group large orders that we split into multiple Harmony orders.
Also fixed the annoying database problem in dev where we say "sorry, too many clients already" by forcing idle connections to be disconnected.
Harmony orders
Submit a harmony order, check the labels added
=> EDSC-4292: Adds label to Harmony orders

static/src/js/components/OrderStatus/OrderStatusItem.jsx, static/src/js/components/OrderStatus/OrderStatusItem/DownloadFilesPanel.jsx, static/src/js/components/OrderStatus/OrderStatusItem/__tests__/DownloadFilesPanel.test.js, static/src/js/components/OrderStatus/__tests__/OrderStatusItem.test.js, static/src/js/components/TextWindowActions/TextWindowActions.jsx, static/src/js/components/TextWindowActions/__tests__/TextWindowActions.test.js
Harmony orders can complete with errors but still have valid links. When this happens we are not showing the Earthdata Download download button.
Change our logic to allow for complete_with_errors jobs that do have links to show the EDD button.
Harmony orders
This job has a bounding box that doesn't work for the a granule within the applied temporal. Ensure that both temporal and spatial subsetting are selected.
http://localhost:8080/projects?p=C2670138092-NSIDC_CPRD!C2670138092-NSIDC_CPRD&pg[1][v]=t&pg[1][gsk]=-start_date&pg[1][m]=harmony0&pg[1][cd]=f&pg[1][ets]=t&pg[1][ess]=t&q=ATL06&sb[0]=-50.99141%2C68.31574%2C-47.56861%2C69.91401&qt=2019-02-22T19%3A47%3A47.080Z%2C2019-04-11T10%3A04%3A08.643Z&ff=Customizable&tl=1553331766!3!!
Locally you will have to submit the job manually, and fetch …
=> EDSC-4246: Show the EDD button when a Harmony order is complete_with_errors and has links

static/src/js/components/Button/Button.jsx, static/src/js/components/Legend/Legend.scss, static/src/js/components/SecondaryToolbar/SecondaryToolbar.jsx, static/src/js/components/SecondaryToolbar/SecondaryToolbar.scss, static/src/js/components/SecondaryToolbar/__tests__/SecondaryToolbar.test.js, static/src/js/components/Tour/SearchTour.scss, static/src/js/components/Tour/TourSteps.jsx, tests/e2e/tour/tour.spec.js
Updates the secondary toolbar with the improvements post the design. This includes adding tool-tips on the buttons in the secondary tool-bar header and some styling improvements to the tour. It also fixes the spacing discrepancy between the colormap and the scale in leaflet when a colormap is rendered
Updating the styling for the Tour steps, secondary toolbar, and the colormap
Secondary toolbar, Leaflet colormap, the tour steps visuals
- **Environment for testing:*Any*
- **Collection to test with:*C1601063219-NSIDC_ECS* (For the colormap)
1. Ensure that hovering over the following buttons displays a tool-tip (My Project, Save Project, Login, Tour button
2. Ensure that the tour steps continue to work as expected with the following differences: the final page for the webinar has been …
=> EDSC-4302: Update the secondary toolbar to include updated designs as well as leaflet controls

serverless/src/scaleImage/utils/cmr/getBrowseImageUrlFromConcept.js, sharedUtils/__tests__/isLinkBrowse.test.js, sharedUtils/getBrowseUrls.js, sharedUtils/isLinkBrowse.js, static/src/js/components/GranuleResults/GranuleResultsFocusedMeta.jsx
When displaying granule thumbnails, if the metadata lists s3 and https browse links but the s3 link comes first we are trying to fetch that image, which fails.
When filtering granule links to check for the browse rel, also check the protocol of the href to ensure it is http or https
Concept thumbnails, browse imagery
This collection and granule in UAT have the right conditions (s3 and https browse links). Loading this page should show the granule thumbnail correctly and not show the "No Image Available" thumbnail
http://localhost:8080/search/granules?p=C1262899916-LARC_CLOUD&pg[0][v]=f&pg[0][id]=TEMPO_NO2_L2_V03_20240801T235308Z_S016G04.nc&pg[0][gsk]=-start_date&ee=uat&q=TEMPO_NO2_L2_V03&tl=1729082839!3!!&lat=38.3203125&long=-131.0625
=> EDSC-4320: Updates browse image logic to include a check for http/https

static/src/js/util/__tests__/facets.test.js, static/src/js/util/facets.js
Fixes issue where empty string titles in cmr metadata causes edsc to throw errors when trying to call toUpperCase.
Added util function to safely do this, refactored relevant to use new util.
getStartingLetters and buildOrganizedFacets in facets.js util
Added tests for these two functions and new util function getNormalizedFirstLetter
A little tricky to test, in environment as it needs bad facet metadata.  However locally you can add on line 89 in viewAllFacets.js reducer to replicate the problem, 
```
payload.facets = payload.facets.map((facetCategory) => {
if (facetCategory.title === 'Projects') {
return {
...facetCategory,
children: [...facetCategory.children, { title: '' }]
}
}
return facetCategory
})
```
=> EDSC-4280 fixes issues with view all facet util functions

sharedConstants/nonIndexedCmrKeys.js, sharedConstants/permittedCmrKeys.js, static/src/js/util/collections.js, static/src/js/util/request/__tests__/collectionRequest.test.js
Adds toolConceptId as a permitted parameter
Portal can now use the toolConceptId
Follow the [Portal Creation Guide](https://wiki.earthdata.nasa.gov/display/EDSC/Portal+Creation+Guide) to create a test portal with the toolConceptId parameter as part of your query.
=> EDSC-4389: Adds toolConceptId as a permitted parameter

static/src/js/components/CollectionResults/CollectionResultsItem.scss, static/src/js/components/SecondaryToolbar/SecondaryToolbar.jsx, static/src/js/components/Tour/SearchTour.jsx, static/src/js/components/Tour/SearchTour.scss, static/src/js/components/Tour/TourSteps.jsx, tests/e2e/tour/tour.spec.js
- Adding logic to show the `+` and `ⓘ` buttons on step 8 of the tour which are normally only visible when hovering a collection.
- Adding a footnote to let users know they can navigate the tour using arrow keys.
- Adding logic to handle the hiding/showing of `+` and `ⓘ` on the first collection for slide 8.
- Adding a note to let the users know about navigation hotkeys.
- Search Tour
1. Start the Tour
2. Verify that the first slide has a footnote about the users being able to navigate using the arrow keys
3. Verify that slide 8 which talks about the `+` and `ⓘ` buttons are shown on the first collection in the list.
=> EDSC-4330: Tour adjustments

static/src/js/components/SpatialDisplay/SpatialSelectionDropdown.jsx, static/src/js/components/SpatialDisplay/SpatialSelectionDropdown.scss, static/src/js/components/SpatialDisplay/__tests__/SpatialSelectionDropdown.test.js, static/src/js/components/SpatialSelection/SpatialSelection.jsx, tests/e2e/map/map_spatial.spec.js
Ensuring the spatial buttons and consistent in both order and style, and adding aria-labels to them.
Updating the icons for spatial filter buttons to all match the same visual style. Making the spatial dropdown filters be left-aligned. Adding aria-labels to all the spatial filter buttons.
- Spatial Filter Dropdown
- Leaflet Spatial Filter Buttons
1. Verify that the Spatial Filter Dropdown is left aligned and that the styles and order match the leaflet buttons.
2. Ensure all buttons still work as expected.
=> EDSC-4349: Adjustments to spatial filter dropdowns and buttons

static/src/js/components/GranuleFilters/GranuleFiltersForm.jsx, static/src/js/components/GranuleFilters/__tests__/GranuleFiltersForm.test.jsx, static/src/js/components/TemporalDisplay/TemporalSelectionDropdown.jsx, static/src/js/components/TemporalSelection/TemporalSelection.jsx
During testing, two issues were identified with the current implementation:
1. Collection Temporal Slider: When no dates are set, manipulating the end date slider simultaneously affects the minimum/start date slider.
2. Granule Temporal Filter: When the recurring option is toggled on, the sliders don't respond to the first onChange event. However, after clicking and releasing the sliders once, they begin functioning normally.
In both the TemporalSelectionDropdown and GranuleFiltersForm components, we initialization values for start and end dates in their respective onSliderChange callbacks. For TemporalSelectionDropdown, this was implemented using utc() when creating the moment objects.
Temporal Selection recurring slider on granule and collection filters.
- …
=> EDSC-4125: Recurring temporal slider doesn't work

static/src/js/components/EDSCIcon/EDSCIcon.jsx, static/src/js/components/EDSCIcon/EDSCIcon.scss, static/src/js/components/EDSCIcon/__tests__/EDSCIcon.test.jsx, static/src/js/components/Facets/Facets.jsx, static/src/js/components/Facets/FacetsItem.jsx, static/src/js/components/Facets/FacetsItem.scss, static/src/js/components/Facets/__tests__/Facets.test.jsx
The Facets for the "Available in Earthdata Cloud" and "Map Imagery" Should have icons added to them these should match icons used in static/src/js/components/CollectionResults/CollectionResultsItem.jsx for consistency
Facets and FacetItem components will allow for adding of icons to facets via a new icon prop
Facets.jsx and FacetsItem.jsx
On main search page with collection results, there should now be icons for cloud and map imagery feature
[facets](<img width="301" alt="Screenshot 2025-01-29 at 8 00 46 AM" src="https://github.com/user-attachments/assets/32cbd37c-fc41-4a51-89d4-d6290709cc96" />)
=> EDSC-4342: Adds features facet icons

.gitignore, package-lock.json, package.json, static/src/js/components/CollectionResults/CollectionResultsItem.jsx, static/src/js/components/CollectionResults/__tests__/CollectionResultsItem.test.jsx, static/src/js/components/EDSCIcon/EDSCIcon.jsx, static/src/js/components/GranuleResults/GranuleDownloadButton.jsx, static/src/js/components/GranuleResults/GranuleResultsActions.scss, static/src/js/components/GranuleResultsHighlights/GranuleResultsHighlights.scss, static/src/js/components/MetaIcon/MetaIcon.jsx, static/src/js/components/MetaIcon/MetaIcon.scss, static/src/js/components/MetaIcon/__tests__/MetaIcon.test.jsx, static/src/js/components/NotAvailableIcon/NotAvailableIcon.jsx, static/src/js/components/NotAvailableIcon/__tests__/NotAvailableIcon.test.jsx, static/src/js/components/SearchPanels/SearchPanels.jsx, static/src/js/components/SearchPanels/__tests__/SearchPanels.test.jsx, static/src/js/components/Timeline/Timeline.scss
Indicate when collections don't have features.
Various other visual updates found after the bootstrap upgrade.
We are now always showing the 3 feature facet icons in the collection results list. When the collection does not have that feature we are displaying a slash through the icon, and updating the tooltip accordingly.
Collection results list items
View the collection results list. Check/uncheck the feature facets to see variations of icons
=> EDSC-4345: Indicate when collections don't have features

.github/bundle-size-comment-template.md, bin/compareBundleSize.mjs, static/src/js/containers/AuthTokenContainer/AuthTokenContainer.jsx, static/src/js/containers/AuthTokenContainer/__tests__/AuthTokenContainer.test.jsx
When we disable database components, like for a maintance window, we need to log out the user to ensure that they are not sending requests to our API
Search requests when the config value `disableDatabaseComponents` is set to `"true"`
Login, then set `disableDatabaseComponents` to `"true"` in overrideStatic.config.json. Vite will reload the page, check the network tab in your browser devtools to ensure that the collections request went directly to CMR, and not to localhost:3001
=> EDSC-4351: Logs out user when database components are disabled

serverless/src/util/getQueueUrl.js, static/src/js/components/Legend/Legend.scss, static/src/js/components/Legend/LegendControl.jsx, static/src/js/components/Map/Map.jsx, static/src/js/components/Map/Map.scss, static/src/js/containers/MapContainer/MapContainer.jsx, tests/e2e/map/map_granules.spec.js
Add the existing Legend component into the OpenLayers controls framework
Created a OpenLayers control (LegendControl.jsx) wrapping the Legend.jsx component, added into the OpenLayers map controls object, moved the existing gibs color map logics into MapContainer, added/moved css into Map.scss file to css the new LegendControl, reenabled and fixed color map playwright e2e tests.
The new OpenLayers map is impacted.
- Prod data
- C1243477369-GES_DISC
1. Search C1243477369-GES_DISC
2. Navigate to focused collection page
3. Verify colormap/legend is rendered with the other map controls
=> EDSC-4423 Render colormaps on the open layers map

static/src/js/components/Button/Button.jsx, static/src/js/components/Button/__tests__/Button.test.jsx, static/src/js/components/EDSCTable/EDSCTable.jsx, static/src/js/components/GranuleResults/GranuleResultsDataLinksButton.jsx, static/src/js/components/GranuleResults/GranuleResultsItem.jsx, static/src/js/components/GranuleResults/GranuleResultsTable.jsx, static/src/js/components/GranuleResults/GranuleResultsTableHeaderCell.jsx, static/src/js/components/GranuleResults/__tests__/GranuleResultsDataLinksButton.test.jsx
Adding missing Download granule tooltip for granules with only one file
Added the tooltip and tooltipId to the button for the single file path cleaned up extra labels on the other buttons and this one. Removed the title from the table row so that it does not appear when hovering over buttons in table view
Tooltip for single granule downloads; EDSC table; granule results on the table view
1. Go to https://search.earthdata.nasa.gov/search/granules?p=C179001903-SEDAC&pg[0][v]=f&pg[0][gsk]=-start_date&fdc=Socioeconomic%20Data%20and%20Applications%20Center%20(SEDAC)&as[organization][0]=Socioeconomic%20Data%20and%20Applications%20Center%20(SEDAC)&tl=1739469321.207!3!!&lat=80.015625
2. Hover your mouse over the download button for the …
=> EDSC-4406: "Download granule data" tooltip is not showing for single granule downloads

static/src/js/components/Facets/FacetsItem.jsx
Commafying the facet item totals
Calling commafy on the total
Facets and the Facet modals
Navigate to EDSC and view the Facet lists. Make sure any facets over 999 have commas.
=> EDSC-3620: Commafying FacetsItems totals

static/src/css/modules/_links.scss, static/src/js/components/CollectionDetails/CollectionDetailsCloudAccessInstance.jsx, static/src/js/components/ExternalLink/ExternalLink.jsx
For separated links, the underline and spacing was displaying incorrectly.
Updated CSS to utilize transform and translateX to center the separator, changed the pseudo element before child (the separator) to use an absolute position relative to its parent(the link), added margin left to the parent to adjust and make room for the separator on every child but the first child.  This avoids the margin being included in the first link in a list.
_link.scss, CollectionDetailsCloudAccessInstance.jsx, S3LinksPanel.jsx, GranuleResultsDataLinksButton.jsx
1. Navigate to collection details page.
2. View relatedUrl links.
3. Navigate to granule results page.
4. Click download granule data button
5. Select AWS S3 Access
6. View AWS S3 Credentials: links
=> EDSC-4285: Improve display of links on cloud access panel on granule results

static/src/js/components/Facets/FacetsItem.jsx
Commafying the facet item totals
Calling commafy on the total only if facet.count is defined.
Facets and the Facet modals
Navigate to EDSC and view the Facet lists. Make sure any facets over 999 have commas.
Make sure any facets with 0 such as NISAR are the same color as other totals.
=> EDSC-3620: Commafying the facet item totals with explicit check for undefined count

static/src/js/components/Timeline/Timeline.scss
Fixes issue with the timeline collection names
Temporarily adding some overrides in Earthdata Search to fix some unintended overrides. Long term, this will be fixed in Timeline via EDSC-4473.
Timeline
- **Collection to test with:** Any
1. Focus on a collection and view the timeline
2. Confirm text is displayed as intended
Improved collection names:
=> EDSC-4386: Improving display of collection names in timeline

static/src/js/routes/Home/Home.tsx
Fixes an issue where the landing page would scroll when clicking the button to expand or collapse the additional portals on the homepage.
Changed the method we are using to autofocus on the search input, which was triggering when the button was clicked
Landing page
- **Collection to test with:** N/A
1. View the landing page
2. Click the view all portals button to show the portals
3. Confirm the page does not scroll
4. Click the hide all portals button to hide the portals
5. Confirm the page does not scroll
=> EDSC-4386: Fixing scroll issue on landing page

static/src/js/App.jsx, vite.config.mts
Lower index.js size by more lazy loading and implementing manual chunks in build
Index.js size, page load speed
General regression testing
Locally you should be sure to use a production build (`npm run build && npm run preview`). If you want to log in you will also need to run an `npm start` or `npm run start:optionals` _after_ the preview is up on port 8080
=> EDSC-4480: Lower index.js size by more lazy loading and implementing manual chunks in build

static/src/js/App.jsx
The ChunkedOrderModalContainer was being loaded on the `/search` route and not on the `/projects` route, where it is needed.
Submitting an order with more than 2000 granules
Submitting [this project](http://localhost:8080/projects?p=!C1908350066-LPDAAC_ECS&pg[1][v]=t&pg[1][m]=esi0&pg[1][cd]=f&q=C1908350066-LPDAAC_ECS&tl=1650438374.511!4!!) should show the modal
=> EDSC-4480: Fixes ChunkedOrderModalContainer

static/src/js/containers/AuthCallbackContainer/AuthCallbackContainer.jsx
Implementing Zustand has broken the EDD redirect after the user logs in. UrlQueryContainer is being re-rendered an extra time because Redux props are changing, but the Zustand store is also changing. A `setTimeout` in AuthCallbackContainer wrapping the redirect to `/earthdata-download-callback` solves this issue, but it should be removed after UrlQueryContainer is removed (after Zustand is handling the URL)
Earthdata Download redirects
Delete your token from EDD, then start a new download. You will get redirected through EDSC to login with EDL, then ensure EDSC redirects you back to EDD
=> EDSC-4502: Fixes bug in EDD redirect

static/src/js/components/AdminRetrievalsMetrics/__tests__/AdminRetrievalsMetrics.test.jsx, static/src/js/components/AdminRetrievalsMetrics/__tests__/AdminRetrievalsMetricsList.test.jsx, static/src/js/components/TemporalDisplay/TemporalSelectionDropdown.jsx, static/src/js/components/TemporalDisplay/TemporalSelectionDropdownMenu.jsx, static/src/js/components/TemporalDisplay/__tests__/TemporalSelectionDropdownMenu.test.jsx
Fixes the functionality of admin retrievals metrics and using the temporal selection dropdown from the granules page by accounting for the unique feature of when we are on the homepage
Passing in an isHome prop in the temporal selection compoennt flow. 
This will fix an existing issue on that admin component created during the landing page rewrite
1. In database, spoof multiple entries across various date ranges (if necessary)
2. Go to - http://localhost:8080/admin/retrievals-metrics
4. Ensure you see two textboxes that open a calendar view when clicked
5. Enter a valid date range (try for both calendar selection and manual entry)
6. Ensure appropriate metrics are generated
Please include relevant screenshots or files that …
=> EDSC-4479: Fix temporal selection dropdown uses outside of the landing page

static/src/js/actions/__tests__/focusedCollection.test.js, static/src/js/actions/focusedCollection.js, static/src/js/zustand/slices/__tests__/createQuerySlice.test.ts, static/src/js/zustand/slices/createQuerySlice.ts, static/src/js/zustand/types.ts
With the addition of the query zustand slice a bug was introduced that would cause the first page of granule results to be fetched twice. This was because I had changed a call to initialize a granule query to use the `changeGranuleQuery` function, which triggers a call to `getSearchGranules`. 
This PR reintroduces the `initializeGranuleQuery` call, which is resonsible for defaulting the sort key query to the correct value based on user preferences.
Navigating to the granule results list from the collection results list
Click on the first collection result while watching the network dev tools, ensure only one request is called for fetching granules
=> EDSC-4514: Fixes issue with double fetching granules

static/src/js/actions/__tests__/viewAllFacets.test.js, static/src/js/actions/viewAllFacets.js
Fixes issue with View All facets modal not requesting increased page size
With the move to Zustand the `selectedCategory` for ViewAll Facets was lost. This PR puts it in the expected location to ensure the modal works correctly. This will be fixed properly when the facets are moved to Zustand in a future ticket.
View All facets modal
Click the View All link for a facet, ensure more than 50 facets are available in the modal
=> EDSC-4567: Fixes issue with View All facets modal not requesting increased page size

bin/deploy-bamboo.sh, static.config.json, static/src/js/App.jsx, static/src/js/components/EmergencyNotification/EmergencyNotification.jsx, static/src/js/components/EmergencyNotification/__tests__/EmergencyNotification.test.jsx
Adds an emergency notification banner configurable during deployments
A new banner
Locally set the `application.emergencyNotification` to the message you want to be displayed. `emergencyNotificationType` of `error` will show the banner with a red background
=> EDSC-4579: Adds an emergency notification banner configurable during deployments

static/src/js/components/AccessMethod/AccessMethod.jsx, static/src/js/components/Panels/Panels.jsx, static/src/js/zustand/useEdscStore.ts
1. Fixes panels tooltip
2. Fixes error in loading a project page directly with added granules
3. Enables Zustand devtools in production builds
Panels, project page
1. Ensure the panels handle tooltip works as expected.
2. Navigate directly to a [project page with added granules](http://localhost:8080/projects?p=C2515837343-GES_DISC!C2515837343-GES_DISC&pg[1][a]=2519682101!2519682091!GES_DISC&pg[1][v]=t&pg[1][gsk]=-start_date&pg[1][m]=download&pg[1][cd]=f&ee=prod), ensure page loads correctly
3. run `npm run build && npm run preview`, load page and ensure that Redux devtools is showing the Zustand store
=> EDSC-3595: Fixes panels tooltip, fixes error in loading a project page directly

static/src/js/components/Banner/Banner.scss, static/src/js/zustand/slices/__tests__/createQuerySlice.test.ts, static/src/js/zustand/slices/createQuerySlice.ts
Ensure new granule request happens after excluding a granule
The logic that was added to `getGranules` to avoid duplicate requests is keeping this request from happening. To ensure the filtered requests isn't seen as duplicate, reset the `granules.granules.collectionConceptId` before calling `getGranules`
Filtering granules from granule results
- Select a collection with granules, take note of total number of granules
- Filter out a granule by clicking on the the more actions button on a granule to "Filter Granule"
- Ensure granule is removed from granule list, removed from map, and total number of granules is 1 less than before
=> EDSC-4580: Ensure new granule request happens after excluding a granule

serverless/src/submitSwodlrOrder/__tests__/handler.test.js, serverless/src/submitSwodlrOrder/__tests__/retrieveCMRGranules.test.js, serverless/src/submitSwodlrOrder/retrieveCMRGranules.js
- Fixing the `creation failed` error on the SWODLR download status page.
- This was because we were not sending all the `granule_params` with our request to cmr.
- Send all the `granule_params` for Swodlr orders, not just granule `concept_id`
- **Collection to test with:** SWOT Level 2 Water Mask Raster Image Data Product, Version C (C2799438271-POCLOUD)
1. Select a couple granules that support SWODLR orders (use `*_011_424_027*` for granule id filtering)
2. Click Download
3. On the Access Method panel, select SWODLR
4. Click Download Data
5. Ensure that the order succeeds
=> EDSC-4573 - Fixing swodlr order
