app/assets/javascripts/models/data/xhr_model.js.coffee
app/assets/javascripts/models/ui/state_manager.coffee
app/assets/javascripts/modules/autocomplete.js.coffee
app/assets/javascripts/modules/master_overlay.coffee
spec/features/datasets/dataset_keyword_search_spec.rb
spec/features/granules/granule_details_spec.rb

EDSC-540: Make keyword search changes redirect to dataset page

---

edsc/plugins/datasource/cwic/src/js/edsc-plugin.datasource.cwic.jsx

Reverts nasa/earthdata-search#107

Revert "EDSC-818: Download CWIC granules."

---

app/assets/javascripts/modules/map/leaflet-plugins/spherical_polygon.js.coffee

Fix glitchy rendering of polygons which cross the antimeridian in the same direction twice in a row

EDSC-928: Fix glitchy rendering of polygons

---

app/assets/javascripts/config.js.coffee.erb
app/assets/javascripts/models/data/collection.js.coffee
app/assets/javascripts/models/data/granule.coffee
app/assets/stylesheets/modules/panel_list.css.scss
app/views/search/_collection_list_item.html.erb
spec/features/collections/collection_results_spec.rb
spec/features/cwic/granules/cwic_granule_visualizations_spec.rb

browse-scaler changes are on branch ```feature/echo-592``` in ```echo-browser-scaler``` which is behind firewall (not in stash), so no pull request for that :(
Well, the best way to review this is through a gotomeeting so that you don't have to set up the ECHO stack.

ECHO-592 Change border corder of browse image container.

---

edsc/plugins/renderer/cwic/src/js/edsc-plugin.renderer.cwic.jsx

Fix issue where CWIC visualization plugin gets unloaded

---

app/assets/stylesheets/modules/panel_list.css.scss
app/views/search/_granule_list.html.erb

Slight refactor of action item positioning on collection list so that granule action items behave the same way.

EDSC-1116: Fix granule list action item positioning.

---

app/views/granules/prepare_script.html.erb

Signed-off-by: Matthew Crouch <matthew@element84.com>

EDSC:1168 Changed call to innerHTML to textContent

---

doc/edp/edsc-overview.md

@macrouch @mightynimble @jsiarto  Please review this for accuracy, spelling, and grammar. This content will be ingested by the Earthdata Developer Portal, which goes live next week. Assuming things look good upon your review, please go ahead and merge this for me since I'll be out. Thanks guys.

EDP-198: Add overview documentation for Earthdata Developer Portal.

---

app/views/granules/prepare_script.html.erb
spec/features/data_access/data_download_spec.rb

EDSC-1206 Fix download button in firefox and IE

---

app/assets/javascripts/modules/map/leaflet-plugins/projection_switcher.js.coffee
spec/features/map/map_interface_spec.rb

Updating geographic projection icon title text to something a little less confusing.

EDSC-1222: Update geographic projection title text.

---

app/services/esi_client.rb
fixtures/cassettes/collections_requests.yml
fixtures/cassettes/concepts_requests.yml
fixtures/cassettes/concepts_responses.yml
fixtures/cassettes/data_quality_summary_definitions_requests.yml
fixtures/cassettes/data_quality_summary_definitions_responses.yml
fixtures/cassettes/granules_requests.yml
fixtures/cassettes/hand-edited_requests.yml
fixtures/cassettes/hand-edited_responses.yml
fixtures/cassettes/option_definitions_requests.yml
fixtures/cassettes/option_definitions_responses.yml
fixtures/cassettes/order_information_requests.yml
fixtures/cassettes/order_information_responses.yml
fixtures/cassettes/service_option_assignments_requests.yml
fixtures/cassettes/service_option_assignments_responses.yml
fixtures/cassettes/service_option_definitions_requests.yml
fixtures/cassettes/service_option_definitions_responses.yml
fixtures/cassettes/timeline_requests.yml
fixtures/cassettes/timeline_responses.yml
spec/features/data_access/service_options_with_bad_bounding_box_spec.rb
spec/features/data_access/service_options_with_boundingbox1_spec.rb

these specific echoforms used `boundbox1` instead of `boundingbox` I copied the `find_by_xpath` call from Reverb to fix the issue

EDSC-1233 fix ESI Service request bbox coordinates

---

app/assets/javascripts/models/data/query.js.coffee
config/environments/test.rb
edsc/plugins/datasource/cmr/src/js/edsc-plugin.datasource.cmr.jsx
fixtures/cassettes/collections_requests.yml
fixtures/cassettes/granules_requests.yml
fixtures/cassettes/timeline_requests.yml
fixtures/cassettes/timeline_responses.yml
spec/features/granules/granule_filters_spec.rb
spec/features/granules/granule_list_spec.rb

This is from Matthew's branch.

EDSC-1231 inherit project from collection query into granule query

---

config/portals.yml

creating a custom portal to search all but only ORNL DAAC data sets and granules
Please check that I picked the right param
- Daine Wright

add ORNL DAAC portal

---

spec/features/address_bar_spec.rb
spec/features/cwic/granules/cwic_granule_exclusion_spec.rb
spec/features/data_access/single_granule_access_spec.rb
spec/features/granules/granule_filters_spec.rb
spec/features/granules/granule_list_spec.rb
spec/features/help/site_tour_spec.rb
spec/features/landing_page_spec.rb
spec/features/map/colormap_spec.rb
spec/features/map/granule_selection_spec.rb
spec/features/portals/portal_parameter_spec.rb
spec/features/projects/saving_projects_spec.rb
spec/features/site_preferences_spec.rb
spec/features/system_events_spec.rb
spec/features/users/contact_information_spec.rb
spec/features/users/expired_token_spec.rb
spec/helpers/collection_helpers.rb

This gets it down to 15 failures - many remaining failures are tied together, so fixing one bug can fix anywhere from 2 to 5 failures, depending.

Edsc 1361 test updates

---

README.md

Updates NLP URL in the Github readme.

EDSC-1375: Updates NLP URL.

---

app/assets/javascripts/util/xhr.js.coffee.erb
spec/features/map/granule_selection_spec.rb

This is a 'hot fix' to (hopefully) repair the stalled labs-ux merge.

Labs-ux: Updated Test

---

app/assets/javascripts/models/ui/project_list.js.coffee
app/assets/stylesheets/modules/data_access.css.scss
app/views/data_access/retrieval.html.erb
spec/features/data_access/data_download_spec.rb

…lity to hide it at appropriate time
The data access header 'Success' message was changed to: 
_Request in Progress:  Your request is being processed.  Results will appear shortly._
This message disappears once the results have been obtained.
Do we need a test for this?  It feels so innocuous and tiny as to not need one - let me know.

EDSC-1303: Updated header message for data access and modified visib

---

app/assets/javascripts/modules/map/map.js.coffee
app/assets/javascripts/util/xhr.js.coffee.erb
spec/features/granules/granule_filters_spec.rb
spec/features/map/map_zooming_spec.rb

Granule_filters was fixed as a bonus.  These changes were tested on Travis by restarting the build six times; the build went green every time.
This PR replaces the 'FlakyTestFinder' that I was using as a sandbox.

EDSC-1449: Updated map_zooming test as needed for new UI

---

app/assets/stylesheets/modules/data_access.css.scss
app/views/data_access/retrieval.html.erb

EDSC-1428: Added recent retrieval link to success page

---

app/assets/stylesheets/modules/map/map.css.scss
app/views/search/_spatial_manual_entry.html.erb

Filter stack should now consistently respond to both Shape files and polygons. All removal and cancel buttons seem to be working.

EDSC-1447: Fixed Shape File / Filter Stack behavior

---

app/views/search/index.html.erb

Settle in and take some time to review this monster.

EDSC-1489: Fix invalid markup issue.

---

app/assets/stylesheets/modules/echoforms.css.scss
app/assets/stylesheets/modules/map/map.css.scss

Given how echoforms works and current state of markup and style--this is the best we're going to get.

EDSC-1496: Remove dead space on echoforms bounding box

---

app/views/layouts/application.html.erb

Removing FBM from Tophat as there's more FBM stuff going on than I realized. Need to work that separately.

EDSC-1517: Remove FBM from tophat for time being.

---

app/controllers/health_controller.rb
app/models/health.rb
spec/controllers/health_spec.rb

EDSC-1368 Return 503 whenever our dependencies returns a status code larger than 499.

---

app/assets/javascripts/models/data/granule.coffee
spec/features/granules/granule_list_spec.rb

This PR fixes the single granule download issue in UAT and PROD

EDSC-1572 Fix a typo

---

app/assets/javascripts/modules/landing.js.coffee
app/assets/stylesheets/modules/landing.css.scss
app/views/search/index.html.erb

The issue was caused by a remnant of the old landing page - it was set to hide itself upon page load.  However, if the page load lags for a moment, it's visible for a split second before it gets hidden - such was the bug.
Removed the remnant and it looks good now.

EDSC-1499: Cleaned up remnant of original landing page

---

app/assets/javascripts/models/data/collection.js.coffee
app/assets/stylesheets/modules/collection_details.css.scss
app/assets/stylesheets/modules/master_overlay.css.scss
app/presenters/collection_details_presenter_umm_json.rb
app/views/search/_collection_details.html.erb
app/views/search/_data_center_details.html.erb
spec/features/collections/collection_details_presenter_umm_json_spec.rb
spec/features/collections/collection_details_spec.rb
spec/features/cwic/granules/cwic_granule_list_spec.rb

Use this collection in SIT ```C1200235634-EDF_DEV06``` which gives an example on how data centers will look like if all fields are set and when there are multiple. 
Compare it with the MMT layouts:
https://mmt.sit.earthdata.nasa.gov/collections/C1200235634-EDF_DEV06

EDSC-1140 Add more info to data center in collection details.

---

.travis.yml

Attempt to fix the failed master build. Not sure if it will work but I have tested the (bash) script locally to make sure there is no syntax error.

EDSC-1194 Tried to fix the shallow clone issue.

---

app/assets/javascripts/models/ui/project_list.js.coffee
app/assets/javascripts/models/ui/reverb_retirement.coffee
app/assets/stylesheets/modules/collection_details.css.scss
app/assets/stylesheets/modules/modal.css.scss
app/presenters/collection_details_presenter_umm_json.rb
app/views/search/_collection_details.html.erb
app/views/search/_related_urls_modal.html.erb
app/views/search/_reverb_retirement_modal.html.erb
app/views/shared/_back_to_reverb.html.erb
fixtures/cassettes/collections_requests.yml
fixtures/cassettes/concepts_requests.yml
fixtures/cassettes/concepts_responses.yml
spec/features/collections/collection_apis_spec.rb
spec/features/collections/collection_details_presenter_umm_json_spec.rb
spec/features/collections/collection_details_spec.rb

Added code to strip out instances of 'http://' and 'https://', and also added a conditional to check for presence of base url 'dx.doi.org' so that it doesn't contain that string twice.

EDSC-1645: Cleaned up DOI badge

---

app/helpers/portal_helper.rb
app/views/search/index.html.erb
spec/features/portals/portal_escape_link_spec.rb

Creating this in response to #504. I believe this is a faster way to achieve desired results as it looks like that fork is out of date. It has tons of test failures.

Update portal escape link copy.

---

app/assets/javascripts/models/data/granule.coffee
app/assets/stylesheets/modules/panel_list.css.scss
app/views/search/_granule_list.html.erb
fixtures/cassettes/services_requests.yml
fixtures/cassettes/services_responses.yml
fixtures/cassettes/timeline_requests.yml
fixtures/cassettes/timeline_responses.yml
spec/features/granules/granule_list_spec.rb

Keep the 'click-to-download' feature if there is only one link.

EDSC-1641 Introduce a dropdown if a granule has more than one downloadable links.

---

app/assets/javascripts/models/page/project_page.js.coffee
app/assets/javascripts/models/page/search_page.js.coffee
app/assets/javascripts/modules/map/map.js.coffee
app/assets/javascripts/modules/map/spatial_selection.js.coffee
app/assets/javascripts/modules/temporal/temporal_range_selection.js.coffee
app/assets/javascripts/projects.js
spec/features/projects/viewing_project_spec.rb

This update integrates the minimap in a manner that is more inline with the overall architecture.  The 'urlUtil' approach previously taken is no longer necessary; further, the issues found in test - where the spatial coordinates would not load from the saved project - are now working.
This is done by using the spatial selection object to draw the map instead of relying on urlUtil.

EDSC-1613: Updated minimap implementation

---

app/views/search/_collection_list_item.html.erb
app/views/search/_granule_list.html.erb
app/views/search/index.html.erb
spec/features/collections/collection_limited_ondemand_products_spec.rb

https://bugs.earthdata.nasa.gov/browse/EDSC-1752

EDSC-1752: Update limited collections help text

---

app/assets/javascripts/modules/global_hooks.js.coffee

EDSC-1841: Comment out map overaly GA tracking.

---

edsc/portals/ornl/src/js/edsc-portal.ornl.jsx

Portal now includes collections without granules by default.

Added js to ORNLDAAC portal

---

app/assets/stylesheets/modules/panel_list.css.scss
app/views/search/_collection_list_item.html.erb
fixtures/cassettes/collections_requests.yml
spec/features/e2e_services/search/opendap_collection_spec.rb

This will conditionally render the customization badges depending on the options available for a collection in the search results.

EDSC-1728: Added badges to collections in search results

---

app/assets/javascripts/models/ui/project_list.js.coffee
app/models/retrieval.rb

EDSC-1943: Reduces DJ logging and introduces stall period for hydration jobs

---

app/assets/javascripts/modules/help.js.coffee
app/assets/stylesheets/modules/tour.css.scss
config/environments/development.rb

This will improve the display of the facet category titles in the tour. I have also added the tag manager id to the development config file. This will ensure Google Tag Manager is always loaded in development, which we want.

EDSC-1872: Improves display of titles in tour

---

app/assets/stylesheets/modules/buttons.css.scss
app/assets/stylesheets/modules/data_access.css.scss
app/assets/stylesheets/modules/dropdown.css.scss
app/assets/stylesheets/modules/layout.css.scss
app/assets/stylesheets/modules/master_overlay.css.scss
app/assets/stylesheets/modules/panel_list.css.scss
app/assets/stylesheets/modules/settings.css.scss
app/views/search/_granule_list.html.erb
app/views/search/index.html.erb

Took this as an opportunity to flatten the standard buttons. Time would be well spent double checking all cases were covered. I think I got them all, but there may be a few hidden buttons I am not aware of.

EDSC-1888: Improving display of disabled project download button

---

app/assets/stylesheets/modules/collection_details.css.scss
app/assets/stylesheets/modules/echoforms.css.scss
app/assets/stylesheets/modules/master_overlay.css.scss
app/assets/stylesheets/modules/master_overlay_parent.css.scss
app/views/shared/_overlay_parent.html.erb

This PR:
- Disables the echoforms map display on the project panel and improves styling in the project panel
- Fixes issues with link colors in portals
- Improves display of spatial subsetting message

EDSC-2047: Improving display of echoforms on the project page

---

Gemfile
Gemfile.lock
app/assets/javascripts/models/page/project_page.js.coffee
app/models/order.rb
app/views/data_access/_too_many_granules_modal.html.erb
app/views/projects/show.html.erb
app/views/shared/_overlay_parent.html.erb

EDSC-2248: Displays order chunking modal and fixes large orders

---

app/controllers/data_access_controller.rb

Since OrderStatusJobs are now enqueued by the OrderJob base after_perform hook, we can remove this code and prevent enqueuing duplicate OrderStatusJobs.

EDSC-2252: Removes OrderStatusJobs logic from DataAccessController

---

README.md
package-lock.json

Just wanting to join in on the fun.

EDSC-2406: Fix readme typos

---

serverless/src/getAccessMethods/__tests__/handler.test.js
serverless/src/getAccessMethods/handler.js
static/src/js/components/ProjectPanels/ProjectPanels.js
static/src/js/util/__tests__/isProjectValid.test.js
static/src/js/util/isProjectValid.js

EDSC-2388: Pre-populate the email address field in echo forms

---

static/src/js/components/Facets/FacetsItem.scss

Updates the color of facet items in "view all facets" modal.

EDSC-2657: Update style for light variant of modal facet component.

---

portals/idn/config.json

added hasGranulesOrCwic to set to null to include all collections

CMRSCI-3584: added hasGranulesOrCwic to set to null to include all collections

---

README.md

This PR updates the Node and Webpack versions to the currently used ones.

Update Webpack and Node versions

---

static/src/js/components/GranuleResults/GranuleResultsBody.js
static/src/js/util/__tests__/formatGranulesList.test.js
static/src/js/util/formatGranulesList.js

Added additional PropTypes for granulesMetadata

EDSC-2876: Fixes error when granule metadata doesn't contain temporal

---

CONTRIBUTING.md

Updating contribution docs for the start of Hacktoberfest.

Update contribution docs.

---

.github/pull_request_template.md

If accepted, the PR description would be as follows...
Please summarize the feature or fix.
Summarize what you changed.
1. Step 1
2. Step 2...

EDSC-2915: Adds pull request template.

---

static/src/js/components/KeyboardShortcutsModal/KeyboardShortcutsModal.js

Removes trailing comma (that wasn't found in code review)

EDSC-2911: Remove trailing comma

---

package-lock.json
package.json
static/src/js/components/CollectionResults/CollectionResultsListItem.js
static/src/js/components/Timeline/Timeline.js

Updated the timeline component to use the new NPM version of our timeline plugin

EDSC-2942: Update edsc-timeline to use NPM package

---

package-lock.json
package.json
static/src/js/containers/GranuleFiltersContainer/__tests__/validationSchema.test.js
static/src/js/containers/GranuleFiltersContainer/validationSchema.js
static/src/js/util/__tests__/validation.test.js
static/src/js/util/validation.js

EDSC-2965: Updates formik and yup

---

portals/default/config.json
portals/edsc/config.json
static.config.json
static/src/js/actions/__tests__/portals.test.js
static/src/js/actions/__tests__/urlQuery.test.js
static/src/js/components/Facets/Facets.js
static/src/js/components/Facets/__tests__/Facets.test.js
static/src/js/reducers/__tests__/facetsParams.test.js
static/src/js/reducers/facetsParams.js
static/src/js/util/__tests__/portals.test.js
static/src/js/util/collections.js
static/src/js/util/url/__tests__/featureFacetUrl.test.js
static/src/js/util/url/__tests__/url.mocks.js
static/src/js/util/url/featureFacetEncoders.js

Adds 'Available from AWS Cloud' feature facet
Facets

EDSC-3005: Adds 'Available from AWS Cloud' feature facet

---

serverless-configs/aws-resources.yml
serverless/src/processTag/handler.js

Adds logging for an error with a less than helpful stack trace.

EDSC-2986: Adds logging for error debugging

---

static/src/js/components/SubscriptionsList/SubscriptionsList.js

Fixes typo in EDSC-2930
Fixed typo
Subscriptions index page
- **Environment for testing:** ANY
- **Collection to test with:** ANY
1. Confirm typo no longer exists

EDSC-2930: Fixing button label

---

serverless/src/generateGibsTags/__tests__/handler.test.js
serverless/src/generateGibsTags/handler.js

Modifies the way tag collections for gibs imagery.
Rather than using the search criteria in the gibs product for creating tags we run the search and group all requests for tagging by their concept id which prevents race conditions in CMR.

EDSC-3049: Modify the way we create gibs tags

---

package-lock.json
package.json
serverless/src/generateSubsettingTags/getRelevantServices.js
serverless/src/generateSubsettingTags/getServiceOptionDefinitionIdNamePairs.js
serverless/src/generateSubsettingTags/handler.js
serverless/src/storeUserData/__tests__/handler.test.js
serverless/src/storeUserData/handler.js
serverless/src/util/cmr/pageAllCmrResults.js
sharedUtils/__tests__/parseError.test.js
sharedUtils/parseError.js

Some issues have shown up within the store user data lambda.
I've cleaned up the job a bit and added some logging and checks to prevent unnecessary calls from being made.
Storing of authenticated user information for the purposes of ordering data.

EDSC-3088: Adds polish and logging to the storeUserData job

---

serverless/src/cwicGranuleSearch/getCwicGranulesUrl.js
serverless/src/fetchOptionDefinitions/__tests__/handler.test.js
serverless/src/fetchOptionDefinitions/handler.js
serverless/src/generateColorMaps/getProjectionCapabilities.js
serverless/src/generateSubsettingTags/getRelevantServices.js
serverless/src/generateSubsettingTags/getServiceOptionDefinitionIdNamePairs.js
serverless/src/generateSubsettingTags/handler.js
serverless/src/processColorMap/handler.js
serverless/src/storeUserData/handler.js
serverless/src/submitRetrieval/handler.js
serverless/src/util/cmr/getSingleGranule.js
serverless/src/util/cmr/pageAllCmrResults.js
serverless/src/util/cmr/readCmrResults.js

I've added additional logs to lambdas that are randomly timing out.

EDSC-3090: Adds new logs and corrects timing logs

---

serverless/src/util/cmr/__tests__/pageAllCmrResults.test.js
serverless/src/util/cmr/pageAllCmrResults.js

I missed a timing log.
I updated a timing log.

EDSC-3090: Fixes last remaining timing log

---

static/src/js/actions/focusedCollection.js
static/src/js/actions/project.js
static/src/js/components/CollectionDetails/CollectionDetailsBody.js
static/src/js/components/CollectionDetails/CollectionDetailsBody.scss
static/src/js/components/CollectionDetails/__tests__/CollectionDetailsBody.test.js

Adds associated DOIs to the collection details.
Adds associated DOIs to the collection details.

EDSC-3019: Adds associated DOIs to collection details

---

static/src/js/components/AboutCwicModal/AboutCwicModal.js
static/src/js/components/Errors/ErrorBoundary.js

EDSC-3106: Fixes typos

---

package-lock.json
package.json
static/src/js/components/Timeline/Timeline.js
static/src/js/components/Timeline/Timeline.scss
static/src/js/components/Timeline/__tests__/Timeline.test.js
static/src/js/containers/TimelineContainer/TimelineContainer.js
static/src/js/containers/TimelineContainer/__tests__/TimelineContainer.test.js
static/src/js/reducers/timeline.js
static/src/js/util/timeline.js
static/src/js/util/url/__tests__/timelineUrl.test.js
static/src/js/util/url/timelineEncoders.js

Implements the new `@edsc/timeline` plugin 
Timeline

EDSC-3045: Implements new timeline plugin

---

static/src/js/components/CollectionResults/__tests__/CollectionResultsBody.test.js
static/src/js/util/__tests__/formatCollectionList.test.js
static/src/js/util/formatCollectionList.js

Generate the 'Customizable' badges in collection results from the new `service_features` flags in CMR JSON responses

EDSC-3082: Generate 'Customizable' badges from collection metadata

---

static/src/js/util/grid.js

Adds Military Grid Reference System configuration, removes unused grid configuration values

EDSC-3162: Adds Military Grid Reference System configuration

---

static/src/js/components/GranuleResults/GranuleResultsItem.js
static/src/js/components/GranuleResults/GranuleResultsItem.scss
static/src/js/components/GranuleResults/__tests__/GranuleResultsItem.test.js

Disables rounded corner when browse thumbnail is displayed
Disables rounded corner when browse thumbnail is displayed
Granule results list
- **Collection to test with:** C1233200839-LPCLOUDUAT

EDSC-3174: Fixing rounded corner on button when thumbnail is displayed

---

static/src/js/components/Map/GranuleGridLayerExtended.js
static/src/js/util/url/__tests__/addedGranules.test.js
static/src/js/util/url/__tests__/excludedGranules.test.js
static/src/js/util/url/__tests__/projectCollections.test.js
static/src/js/util/url/__tests__/removedGranules.test.js
static/src/js/util/url/collectionsEncoders.js

Also defaults project collections visibility to true

EDSC-3197: Remove the 'Filter Granule' button from the map when viewing the project page

---

package-lock.json
package.json

Updating a few packages for deployments.

EDSC-3233: Updates more packages

---

cypress/integration/paths/search/granules/granules_spec.js
package-lock.json
package.json
static/src/css/modules/_dropdown.scss
static/src/css/utils/mixins/_carat.scss
static/src/js/components/Button/Button.scss
static/src/js/components/GranuleResults/GranuleDownloadButton.js
static/src/js/components/GranuleResults/GranuleResultsActions.js
static/src/js/components/GranuleResults/GranuleResultsActions.scss
static/src/js/components/GranuleResults/__tests__/GranuleResultsActions.test.js
static/src/js/components/Panels/__tests__/Panels.test.js
static/src/js/containers/GranuleResultsActionsContainer/GranuleResultsActionsContainer.js
static/src/js/containers/GranuleResultsActionsContainer/__tests__/GranuleResultsActionsContainer.test.js
static/src/js/util/__tests__/getPanelSizeMap.test.js
static/src/js/util/getPanelSizeMap.js

Improving smart handoffs
Moving the location of the smart handoffs dropdown
Granule results list 
- **Environment for testing:** PROD
- **Collection to test with:**  C1453188197-GES_DISC
1. Visit collection results
2. Confirm smart handoffs button is displayed at the bottom of the window

EDSC-3241: Improve smart handoffs

---

static/src/js/components/GranuleResults/GranuleResultsActions.scss

Fixes the explore button color
Tweak the css
Explore button on granule results page
- **Environment for testing:** Prod
- **Collection to test with:** C1453188197-GES_DISC

EDSC-3241: Fixing button color

---

cypress/integration/map/map_spec.js
cypress/integration/paths/search/granules/collection_details/collection_details_spec.js
cypress/integration/paths/search/granules/granule_details/granule_details_spec.js
cypress/integration/paths/search/granules/granules_spec.js
cypress/integration/paths/search/search_spec.js
cypress/support/interceptUnauthenticatedCollections.js
portals/edsc/config.json
static/src/js/actions/__tests__/urlQuery.test.js
static/src/js/reducers/__tests__/query.test.js
static/src/js/reducers/query.js
static/src/js/util/url/__tests__/hasGranulesOrCwicUrl.test.js
static/src/js/util/url/__tests__/url.mocks.js
static/src/js/util/url/hasGranulesOrCwicEncoders.js

Reverts nasa/earthdata-search#1456

Revert "EDSC-3311: Defaults 'Include collections without granules' to checked"

---

static/src/js/components/Skeleton/Skeleton.scss

Tweaking skeleton css animation
Change animation so it works more consistently across the various implementations.
Skeleton loaders
- **Collection to test with:** Any

EDSC-2991: Tweaking skeleton css animation

---

cypress/integration/map/map_spec.js
cypress/integration/paths/search/granules/granules_spec.js
cypress/support/interceptUnauthenticatedCollections.js
serverless-configs/aws-functions.yml
serverless/src/alertLogger/__tests__/handler.test.js
serverless/src/alertLogger/handler.js
static/src/js/actions/__tests__/accessMethods.test.js
static/src/js/actions/__tests__/alerts.test.js
static/src/js/actions/__tests__/granules.test.js
static/src/js/actions/accessMethods.js
static/src/js/actions/alerts.js
static/src/js/actions/errors.js
static/src/js/actions/focusedCollection.js
static/src/js/actions/granules.js
static/src/js/actions/index.js
static/src/js/actions/urlQuery.js
static/src/js/util/__tests__/retrievals.test.js
static/src/js/util/granules.js
static/src/js/util/request/__tests__/loggerRequest.test.js
static/src/js/util/request/loggerRequest.js

When using the additive method to select granules only the granules selected are analyzed for online_access_flag to determine the available access methods.

EDSC-3352: Use added granule metadata for access methods

---

static/src/js/components/CollectionResults/CollectionResultsItem.scss

Small fix to add some padding on the action buttons on collection results
1. Load SIT and trigger the Thumb Only variant in optimize

EDSC-3416: Fixing issue with button spacing

---

portals/amd/config.json

Updated config.json, on request from AMD provider, with new values for link, title, org, pageTitle for AMD portal.
AMD Portal config.json file.
Please summarize the feature or fix.
New values for link, title, org, pageTitle for AMD portal.
Changed element values in the config file.
Summarize what you changed.
link, title, org, pageTitle for AMD portal.
Local client review of fixes.
- [X ] I have added automated tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] I have performed a self-review of my own code
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings

IDN-81: Update config.json

---

bin/deploy-bamboo.sh
static.config.json
static/src/js/components/ABExperiment/ABExperiment.js
static/src/js/components/ABExperiment/__tests__/ABExperiment.test.js
static/src/js/components/CollectionResults/CollectionResultsItem.js
static/src/js/components/CollectionResults/CollectionResultsList.js
static/src/js/components/CollectionResults/__tests__/CollectionResultsItem.test.js
static/src/js/hooks/__tests__/useExperiment.test.js
static/src/js/hooks/useExperiment.js

Improving A/B testing functionality to enable us to more easily update information about the variants
- Cleaned out unnecessary variants
- Moved the variants mapping to a Bamboo variable
- Collection Search Results List and the ABExperiment component
1. Preview the experiment in Optimize
2. Ensure each variant loads as expected

EDSC-3527: Improving A/B testing functionality

---

package-lock.json
package.json
schemas/sitePreferencesSchema.json
schemas/sitePreferencesUISchema.json
static/src/js/actions/__tests__/focusedCollection.test.js
static/src/js/actions/__tests__/urlQuery.test.js
static/src/js/actions/focusedCollection.js
static/src/js/actions/urlQuery.js
static/src/js/components/Preferences/__tests__/PreferencesForm.test.js
static/src/js/reducers/__tests__/query.test.js
static/src/js/reducers/query.js
static/src/js/selectors/__tests__/preferences.test.js
static/src/js/selectors/preferences.js

Setting the default sorting for collection and granule results as a user preference.
Collection and granule search results.
Visit your user preferences page, set your preference for collection results and granule results.
View search results for collections and granules, ensure correct sorting method is selected.

EDSC-3340: Sets search sorting as a user preference

---

package-lock.json
package.json
serverless/src/fetchCatalogRestOrder/handler.js
serverless/src/generateColorMaps/getProjectionCapabilities.js
serverless/src/getAccessMethods/handler.js
serverless/src/openSearchGranuleSearch/__tests__/getOpenSearchGranulesUrl.test.js
serverless/src/openSearchGranuleSearch/getOpenSearchGranulesUrl.js
serverless/src/processColorMap/handler.js
serverless/src/submitCatalogRestOrder/handler.js
sharedUtils/parseError.js
static/src/js/util/request/__tests__/openSearchGranuleRequest.test.js
static/src/js/util/request/openSearchGranuleRequest.js

Updates the version of fast-xml-parser used
Updated from version 3.x to 4.x
```npm run test```

EDSC-3667 updates fast-xml-parser dependency

---

package-lock.json
package.json

Updates serverless-offline dependency which had a transitive fast-xml-parser dependency

EDSC-3667: updates serverless-offline

---

static/src/js/components/EDSCImage/EDSCImage.js
static/src/js/components/GranuleResults/GranuleResultsFocusedMeta.js
static/src/js/components/GranuleResults/GranuleResultsFocusedMeta.scss

Improving UX in the thumbnail image viewer
Mostly improving display of buttons on varied imagery
Granule browse image thumbnail viewer
- **Environment for testing:** UAT and Prod have better browse imagery
- **Collection to test with:** 
- Any collection with browse imagery should work
- C2021957657-LPCLOUD (1 browse image per granule)
- C1940473819-POCLOUD (4 browse images per granule)
- C2113473491-NSIDC_ECS (13 browse images per granule)

EDSC-3750: Improving thumbnail styles

---

package-lock.json
package.json
static.webpack.config.common.js
static/src/js/components/ABExperiment/ABExperiment.js
static/src/js/components/CollapsePanel/CollapsePanel.js
static/src/js/components/CollapsePanel/__tests__/CollapsePanel.test.js
static/src/js/components/CollectionDetails/CollectionDetailsBody.js
static/src/js/components/Facets/FacetsModalNav.js
static/src/js/components/Facets/__tests__/FacetsModalNav.test.js
static/src/js/components/Map/MouseEventsLayer.js
static/src/js/components/Map/ShapefileLayer.scss
static/src/js/components/Panels/PanelItem.js
static/src/js/components/Panels/__tests__/PanelItem.test.js
static/src/js/containers/MetricsEventsContainer/MetricsEventsContainer.js
static/src/js/containers/MetricsEventsContainer/__tests__/MetricsEventContainer.test.js
static/src/js/events/__tests__/events.test.js
static/src/js/events/events.js
test-env.js

Removes jQuery from the application
Removed all references to jQuery and replaced with vanilla js equivalents.
- static.webpack.config.common.js
- static/src/js/components/ABExperiment/ABExperiment.js
- static/src/js/components/CollapsePanel/CollapsePanel.js
- static/src/js/components/Facets/FacetsModalNav.js
- static/src/js/components/Facets/__tests__/FacetsModalNav.test.js
- static/src/js/components/Map/MouseEventsLayer.js
- static/src/js/components/Panels/PanelItem.js
- static/src/js/containers/MetricsEventsContainer/MetricsEventsContainer.js\
- static/src/js/events/events.js
- Verify the autoscroll behavior on the facets "view all" modal is not affected
- Modal should stay open upon clicking a section link
- Modal should autoscroll the correct section to the top
- Nothing should …

EDSC-3374: Removes jQuery

---

static/src/js/components/FormFields/RadioList/RadioList.js
static/src/js/components/TemporalDisplay/TemporalSelectionDropdown.js
static/src/js/components/TemporalDisplay/__tests__/TemporalSelectionDropdown.test.js

Convert RadioList TemporalSelectionDropdown from class components to functional components.
Converted the TemporalSelectionDropdown test to utilize React Testing Library
Change the files to utilize functional component standards such as 
1) Changing classes to look like this
`const <class name> = (<props>) => {}`
`export default <class name>`
2) Utilizing useState instead of props = {} and setProps
3) Utilizing useEffects for tracking changes in state values
TemporalSelectionDropdown.js
RadioList.js
1. Step 1
2. Step 2...

EDSC-3601: Convert RadioList TemporalSelectionDropdown to functional components

---

LICENSE
README.md

Updated README.md instructions, verifying they work for a new developer on Intel and Apple Silicon Macs.
Clarify required changes in configuration files and paths to PostgreSQL.
Only the README.
Application should run locally from a fresh install by following only the steps in the README.

EDSC-3896: updated setup instructions in readme

---

package-lock.json

Used `npm audit fix` to update NPM packages.

EDSC-3906: update NPM packages

---

package-lock.json
package.json

Updating Axios version
1. Do regression testing following the EDSC regression test guide.

EDSC-3954: Updating Axios version

---

package-lock.json

Fixes vulnerability in EDSC for `server-side request forgery`
Runing `npm audit fix` to update minor version of the dependencies/ update the `package-lock.json` file
Compile time for node-sass as this package is a wrapper for compiling `.scss` files to `css`
Regression testing and using the `snyk cli` tool to verify locally that the vulnerabilities have been fixed 

EDSC-4016: Runing `npm audit fix` to remediate vulnerabilities

---

package-lock.json
package.json

Removes a vul by removing the package that is directly pulling it in
This package has no references to it anywhere in the SC, it is likely an orphaned artifact
Removing this package should have not affect on EDSC since it is not currently being called by any source code, IaC, or deployment script
Ensure that deployment is successful

EDSC-4145: Remove unused dependency `ws`

---

package-lock.json
package.json

Fixes vulnerability in EDSC for server-side request forgery.
Upgraded the Axios package version.
Do regression testing following the EDSC regression test guide.

EDSC-4227: upgrade axios version

---

package-lock.json
package.json
static/src/js/components/AvailableCustomizationsIcons/AvailableCustomizationsIcons.jsx
static/src/js/components/AvailableCustomizationsIcons/AvailableCustomizationsTooltipIcons.jsx
static/src/js/components/EDSCAlert/EDSCAlert.scss
static/src/js/components/EDSCIcon/EDSCIcon.jsx
static/src/js/components/EDSCIcon/__tests__/EDSCIcon.test.jsx
static/src/js/components/GranuleResultsHighlights/GranuleResultsHighlights.jsx
static/src/js/components/MetaIcon/MetaIcon.scss

Fixes icon alignment
Everywhere EDSCIcon is used
Before:
After:

EDSC-4329: Fixes icon alignment

---

cdk/earthdata-search/lib/earthdata-search-functions.ts
cdk/earthdata-search/lib/earthdata-search-stack.ts

Adds generateNotebook bucket that was missed in the initial CDK migration

EDSC-4351: Adds generateNotebook bucket

---

index.html
vite.config.mts

Update fallback page to include application version
The EDSC page when you have javascript disabled
Disable javascript in your browser, visit the application, ensure the version is in your footer

EDSC-4493: Update fallback page to include application version

---

index.html

EDSC-4493: Fixes class attribute

---

package-lock.json

When this ticket was written, synk was telling us that we needed to update apollo/server and axios in order to address the critical vulnerabilites. However after running an npm audit fix, those issues resolved themselves. 
npm audit fix
package-lock
1. Run npm audit and synk test on main
9 vulnerabilities (2 low, 2 moderate, 3 high, 2 critical)
Tested 1295 dependencies for known issues, found 3 issues, 9 vulnerable paths.
3. Run npm audit and synk test on EDSC-4557 
5 vulnerabilities (2 moderate, 3 high) 
Tested 1295 dependencies for known issues, found 1 issue, 2 vulnerable paths.
4. Regression test to ensure the application runs as expected
- [NA] I have added automated tests that …

EDSC-4557: Fix apollo/server and axios Vulnerabilities
